// Frontend Form Configuration for Address Details Step (Stepper 2)
// This replaces the API call to GET /api/forms/RE_addressDetails/fields?is_group=true

import { FrontendFormConfig } from '../types/configTypes';
import { CMS_URL } from '../../../../../Constant';

export const addressDetailsConfig: FrontendFormConfig = {
  formType: 'RE_addressDetails',
  fields: [],
  groupedFields: {
    registeraddress: {
      label: 'Register Address',
      fields: [
        {
          id: 196,
          formType: 'RE_addressDetails',
          fieldName: 'registerLine1',
          fieldLabel: 'Address Line 1',
          fieldType: 'textfield',
          fieldPlaceholder: 'Enter address here',
          fieldOptions: [],
          validationRules: {
            required: true,
            requiredMessage: 'Please fill address line 1',
            maxLength: '60',
            regx: '^[A-Za-z0-9 `~@#$%^&*()_+\\-=,.]+$',
            regxMessage: 'Only alphanumeric, spaces, and `~@#$%^&*()_+-=,. are allowed.',
          },
          fieldOrder: 1,
          fieldOrderGroup: 2,
          isActive: true,
          isUnique: false,
          fieldWidth: 'full',
          languageSlug: 'en',
          fieldGroup: 'registerAddress',
        },
        {
          id: 197,
          formType: 'RE_addressDetails',
          fieldName: 'registerLine2',
          fieldLabel: 'Address Line 2',
          fieldType: 'textfield',
          fieldPlaceholder: 'Enter address here',
          fieldOptions: [],
          validationRules: {
            required: false,
            maxLength: '60',
            regx: '^[A-Za-z0-9 `~@#$%^&*()_+\\-=,.]+$',
            regxMessage: 'Only alphanumeric, spaces, and `~@#$%^&*()_+-=,. are allowed.',
          },
          fieldOrder: 2,
          fieldOrderGroup: 2,
          isActive: true,
          isUnique: false,
          fieldWidth: 'full',
          languageSlug: 'en',
          fieldGroup: 'registerAddress',
        },
        {
          id: 198,
          formType: 'RE_addressDetails',
          fieldName: 'registerLine3',
          fieldLabel: 'Address Line 3',
          fieldType: 'textfield',
          fieldPlaceholder: 'Enter address here',
          fieldOptions: [],
          validationRules: {
            required: false,
            maxLength: '60',
            regx: '^[A-Za-z0-9 `~@#$%^&*()_+\\-=,.]+$',
            regxMessage: 'Only alphanumeric, spaces, and `~@#$%^&*()_+-=,. are allowed.',
          },
          fieldOrder: 3,
          fieldOrderGroup: 2,
          isActive: true,
          isUnique: false,
          fieldWidth: 'full',
          languageSlug: 'en',
          fieldGroup: 'registerAddress',
        },
        {
          id: 199,
          formType: 'RE_addressDetails',
          fieldName: 'registerCountry',
          fieldLabel: 'Country',
          fieldType: 'dropdown',
          fieldPlaceholder: 'Select country',
          fieldMaster: 'countryCode',
          validationRules: {
            required: true,
            requiredMessage: 'Please select country',
            maxLength: '60',
            maxLengthMessage: 'Max length for country is 60',
          },
          fieldOrder: 4,
          fieldOrderGroup: 2,
          isActive: true,
          isUnique: false,
          fieldWidth: 'full',
          languageSlug: 'en',
          fieldGroup: 'registerAddress',
        },
        {
          id: 200,
          formType: 'RE_addressDetails',
          fieldName: 'registerState',
          fieldLabel: 'State / UT',
          fieldType: 'dropdown',
          fieldPlaceholder: 'Select state/ut',
          fieldOptions: [],
          validationRules: {},
          fieldOrder: 5,
          fieldOrderGroup: 2,
          isActive: true,
          isUnique: false,
          fieldWidth: 'full',
          languageSlug: 'en',
          fieldGroup: 'registerAddress',
          conditionalLogic: [
            {
              when: {
                field: 'registerCountry',
                operator: 'equal',
                value: 'India',
              },
              then: {
                fieldType: 'dropdown',
                fieldPlaceholder: 'Select state/ut',
                validationRules: {
                  required: true,
                  requiredMessage: 'Select state',
                  maxLength: '60',
                  maxLengthMessage: 'Max length for state is 60',
                },
              },
              else: {
                fieldType: 'textfield',
                fieldPlaceholder: 'Enter state/ut',
                clearFields: ['registerState', 'registerDistrict', 'registerCity', 'registerPincode'],
                validationRules: {
                  required: false,
                  requiredMessage: 'Enter state',
                  maxLength: '50',
                  maxLengthMessage: 'Max length for state is 50',
                },
              },
            },
          ],
          fieldAttributes: {
            type: 'external_api',
            trigger: 'blur',
            url: `${CMS_URL}/api/masters/state/{registerCountry}/formatted`,
            urlData: 'registerCountry',
            method: 'GET',
            responseMapping: {
              label: 'name',
              value: 'name',
            },
          },
        },
        {
          id: 201,
          formType: 'RE_addressDetails',
          fieldName: 'registerDistrict',
          fieldLabel: 'District',
          fieldType: 'dropdown',
          fieldPlaceholder: 'Select district',
          fieldOptions: [],
          validationRules: {},
          fieldOrder: 6,
          fieldOrderGroup: 2,
          isActive: true,
          isUnique: false,
          fieldWidth: 'full',
          languageSlug: 'en',
          fieldGroup: 'registerAddress',
          conditionalLogic: [
            {
              when: {
                field: 'registerCountry',
                operator: 'equal',
                value: 'India',
              },
              then: {
                fieldType: 'dropdown',
                fieldPlaceholder: 'Select district',
                validationRules: {
                  required: true,
                  requiredMessage: 'Please select district',
                  maxLength: '40',
                  maxLengthMessage: 'Max lengths for district is 40',
                },
              },
              else: {
                fieldType: 'textfield',
                fieldPlaceholder: 'Enter district',
                validationRules: {
                  required: false,
                  requiredMessage: 'Enter district',
                  maxLength: '50',
                  maxLengthMessage: 'Max lengths for district is 50',
                },
              },
            },
          ],
          fieldAttributes: {
            type: 'external_api',
            trigger: 'blur',
            url: `${CMS_URL}/api/masters/district/{registerState}/formatted`,
            urlData: 'registerState',
            method: 'GET',
            responseMapping: {
              label: 'name',
              value: 'name',
            },
          },
        },
        {
          id: 202,
          formType: 'RE_addressDetails',
          fieldName: 'registerCity',
          fieldLabel: 'City/Town',
          fieldType: 'textfield',
          fieldPlaceholder: 'Enter city/town',
          fieldOptions: [],
          validationRules: {},
          fieldOrder: 7,
          fieldOrderGroup: 2,
          isActive: true,
          isUnique: false,
          fieldWidth: 'full',
          languageSlug: 'en',
          fieldGroup: 'registerAddress',
          conditionalLogic: [
            {
              when: {
                field: 'registerCountry',
                operator: 'equal',
                value: 'India',
              },
              then: {
                fieldType: 'textfield',
                fieldPlaceholder: 'Enter city/town',
                validationRules: {
                  required: true,
                  requiredMessage: 'Enter city',
                  maxLength: '60',
                  maxLengthMessage: 'Max length for city is 60',
                  regx: '^[A-Za-z0-9]+( [A-Za-z0-9]+)*$',
                  regxMessage:
                    'City/Town must contain only alphanumeric characters with a single space between words.',
                },
              },
              else: {
                fieldType: 'textfield',
                fieldPlaceholder: 'Enter city/town',
                validationRules: {
                  required: false,
                  requiredMessage: 'Enter city',
                  maxLength: '50',
                  maxLengthMessage: 'Max length for city is 50',
                  regx: '^[A-Za-z0-9]+( [A-Za-z0-9]+)*$',
                  regxMessage:
                    'City/Town must contain only alphanumeric characters with a single space between words.',
                },
              },
            },
          ],
        },
        {
          id: 203,
          formType: 'RE_addressDetails',
          fieldName: 'registerPincode',
          fieldLabel: 'Pin Code',
          fieldType: 'dropdown',
          fieldPlaceholder: 'Select pin code',
          fieldOptions: [],
          validationRules: {},
          fieldOrder: 8,
          fieldOrderGroup: 2,
          isActive: true,
          isUnique: false,
          fieldWidth: 'full',
          languageSlug: 'en',
          fieldGroup: 'registerAddress',
          conditionalLogic: [
            {
              when: {
                field: 'registerCountry',
                operator: 'equal',
                value: 'India',
              },
              then: {
                fieldType: 'dropdown',
                fieldPlaceholder: 'Select pin code',
                validationRules: {
                  required: true,
                  requiredMessage: 'Select PIN CODE',
                  numberValudation: true,
                  maxLength: '6',
                  maxLengthMessage: 'Max length for pincode is 6',
                },
              },
              else: {
                fieldType: 'textfield',
                fieldPlaceholder: 'Enter pin code',
                validationRules: {
                  required: false,
                  requiredMessage: 'Enter PIN CODE',
                  maxLength: '50',
                  numberValudation: false,
                  regx: '^[A-Za-z0-9]+$',
                  regxMessage: 'PIN code can contain only letters and numbers.',
                  maxLengthMessage: 'Max length for pincode is 50',
                },
              },
            },
          ],
          fieldAttributes: {
            type: 'external_api',
            trigger: 'blur',
            url: `${CMS_URL}/api/masters/pincode/{registerDistrict}/formatted`,
            urlData: 'registerDistrict',
            method: 'GET',
            responseMapping: {
              label: 'pincode',
              value: 'pincode',
            },
          },
        },
        {
          id: 204,
          formType: 'RE_addressDetails',
          fieldName: 'registerPincodeOther',
          fieldLabel: 'Pin Code (in case of others)',
          fieldType: 'textfield',
          fieldPlaceholder: 'Enter your other pin code',
          fieldOptions: [],
          validationRules: undefined,
          fieldOrder: 9,
          fieldOrderGroup: 2,
          isActive: true,
          isUnique: false,
          fieldWidth: 'full',
          languageSlug: 'en',
          fieldGroup: 'registerAddress',
          conditionalLogic: [
            {
              when: {
                field: 'registerPincode',
                operator: 'is',
                value: 'other',
              },
              then: {
                validationRules: {
                  required: true,
                  requiredMessage: 'Enter PIN CODE',
                  maxLength: '6',
                  maxLengthMessage: 'Max length for pin code is 6',
                  minLength: '6',
                  minLengthMessage: 'Min length for pin code is 6',
                  numberValudation: true,
                  regx: '^[0-9]{6}$',
                  regxMessage: 'PIN code must be exactly 6 digits.',
                },
              },
              else: {
                validationRules: {
                  required: false,
                  requiredMessage: 'Enter PIN CODE',
                  maxLength: '50',
                  maxLengthMessage: 'Max length for pin code is 50',
                  numberValudation: true,
                },
              },
            },
          ],
        },
        {
          id: 205,
          formType: 'RE_addressDetails',
          fieldName: 'registerDigipin',
          fieldLabel: 'Digipin',
          fieldType: 'textfield',
          fieldPlaceholder: 'Enter digipin',
          fieldOptions: [],
          validationRules: {
            required: false,
            maxLength: '12',
            maxLengthMessage: 'Max length for digipin is 12',
            regx: '^[2-9CFJKLMPT]{3}-[2-9CFJKLMPT]{3}-[2-9CFJKLMPT]{4}$',
            regxMessage:
              'Please enter a valid Digipin (eg: 29C-45F-7JMT). Only digits 2-9 and letters C,F,J,K,L,M,P,T are allowed.',
          },
          fieldOrder: 10,
          fieldOrderGroup: 2,
          isActive: true,
          isUnique: false,
          fieldWidth: 'full',
          languageSlug: 'en',
          fieldGroup: 'registerAddress',
        },
      ],
    },
    correspondenceaddress: {
      label: 'Correspondence Address',
      fields: [
        {
          id: 206,
          formType: 'RE_addressDetails',
          fieldName: 'sameAsCorrespondenceAddress',
          fieldLabel: 'Same as registered address',
          fieldType: 'checkbox',
          fieldPlaceholder: 'Same As Correspondence Address',
          fieldOptions: [],
          validationRules: {
            required: false,
          },
          fieldOrder: 1,
          fieldOrderGroup: 3,
          isActive: true,
          isUnique: false,
          fieldWidth: 'full',
          languageSlug: 'en',
          fieldGroup: 'correspondenceAddress',
          conditionalLogic: [
            {
              when: {
                field: 'correspondenceAddress',
                operator: 'is',
                value: 'checked',
              },
              then: {
                autoFillFields: [
                  'correspondenceLine1',
                  'correspondenceLine2',
                  'correspondenceLine3',
                  'correspondenceCountry',
                  'correspondenceState',
                  'correspondenceDistrict',
                  'correspondenceCity',
                  'correspondencePincode',
                  'correspondencePincodeOther',
                  'correspondenceDigipin',
                ],
                selectedFields: [
                  'registerLine1',
                  'registerLine2',
                  'registerLine3',
                  'registerCountry',
                  'registerState',
                  'registerDistrict',
                  'registerCity',
                  'registerPincode',
                  'registerPincodeOther',
                  'registerDigipin',
                ],
              },
            },
          ],
        },
        {
          id: 207,
          formType: 'RE_addressDetails',
          fieldName: 'correspondenceLine1',
          fieldLabel: 'Address Line 1',
          fieldType: 'textfield',
          fieldPlaceholder: 'Enter address here',
          fieldOptions: [],
          validationRules: {
            required: true,
            requiredMessage: 'Please fill address line 1',
            maxLength: '60',
            regx: '^[A-Za-z0-9 `~@#$%^&*()_+\\-=,.]+$',
            regxMessage: 'Only alphanumeric, spaces, and `~@#$%^&*()_+-=,. are allowed.',
          },
          fieldOrder: 2,
          fieldOrderGroup: 3,
          isActive: true,
          isUnique: false,
          fieldWidth: 'full',
          languageSlug: 'en',
          fieldGroup: 'correspondenceAddress',
        },
        {
          id: 208,
          formType: 'RE_addressDetails',
          fieldName: 'correspondenceLine2',
          fieldLabel: 'Address Line 2',
          fieldType: 'textfield',
          fieldPlaceholder: 'Enter address here',
          fieldOptions: [],
          validationRules: {
            required: false,
            maxLength: '60',
            regx: '^[A-Za-z0-9 `~@#$%^&*()_+\\-=,.]+$',
            regxMessage: 'Only alphanumeric, spaces, and `~@#$%^&*()_+-=,. are allowed.',
          },
          fieldOrder: 3,
          fieldOrderGroup: 3,
          isActive: true,
          isUnique: false,
          fieldWidth: 'full',
          languageSlug: 'en',
          fieldGroup: 'correspondenceAddress',
        },
        {
          id: 209,
          formType: 'RE_addressDetails',
          fieldName: 'correspondenceLine3',
          fieldLabel: 'Address Line 3',
          fieldType: 'textfield',
          fieldPlaceholder: 'Enter address here',
          fieldOptions: [],
          validationRules: {
            required: false,
            maxLength: '60',
            regx: '^[A-Za-z0-9 `~@#$%^&*()_+\\-=,.]+$',
            regxMessage: 'Only alphanumeric, spaces, and `~@#$%^&*()_+-=,. are allowed.',
          },
          fieldOrder: 4,
          fieldOrderGroup: 3,
          isActive: true,
          isUnique: false,
          fieldWidth: 'full',
          languageSlug: 'en',
          fieldGroup: 'correspondenceAddress',
        },
        {
          id: 210,
          formType: 'RE_addressDetails',
          fieldName: 'correspondenceCountry',
          fieldLabel: 'Country',
          fieldType: 'dropdown',
          fieldPlaceholder: 'Select country',
          fieldMaster: 'countryCode',
          validationRules: {
            required: true,
            requiredMessage: 'Please select country',
            maxLength: '60',
            maxLengthMessage: 'Max length for country is 60',
          },
          fieldOrder: 5,
          fieldOrderGroup: 3,
          isActive: true,
          isUnique: false,
          fieldWidth: 'full',
          languageSlug: 'en',
          fieldGroup: 'correspondenceAddress',
        },
        {
          id: 211,
          formType: 'RE_addressDetails',
          fieldName: 'correspondenceState',
          fieldLabel: 'State / UT',
          fieldType: 'dropdown',
          fieldPlaceholder: 'Select state / ut',
          fieldOptions: [],
          validationRules: {},
          fieldOrder: 6,
          fieldOrderGroup: 3,
          isActive: true,
          isUnique: false,
          fieldWidth: 'full',
          languageSlug: 'en',
          fieldGroup: 'correspondenceAddress',
          conditionalLogic: [
            {
              when: {
                field: 'correspondenceCountry',
                operator: 'equal',
                value: 'India',
              },
              then: {
                fieldType: 'dropdown',
                fieldPlaceholder: 'Select state/ut',
                validationRules: {
                  required: true,
                  requiredMessage: 'Select state',
                  maxLength: '50',
                  maxLengthMessage: 'Max length for state is 50',
                },
              },
              else: {
                fieldType: 'textfield',
                fieldPlaceholder: 'Enter state/ut',
                clearFields: ['correspondenceState', 'correspondenceDistrict', 'correspondenceCity', 'correspondencePincode'],
                validationRules: {
                  required: false,
                  requiredMessage: 'Enter state',
                  maxLength: '50',
                  maxLengthMessage: 'Max length for state is 50',
                },
              },
            },
          ],
          fieldAttributes: {
            type: 'external_api',
            trigger: 'blur',
            url: `${CMS_URL}/api/masters/state/{correspondenceCountry}/formatted`,
            urlData: 'correspondenceCountry',
            method: 'GET',
            responseMapping: {
              label: 'name',
              value: 'name',
            },
          },
        },
        {
          id: 212,
          formType: 'RE_addressDetails',
          fieldName: 'correspondenceDistrict',
          fieldLabel: 'District',
          fieldType: 'dropdown',
          fieldPlaceholder: 'Select district',
          fieldOptions: [],
          validationRules: {},
          fieldOrder: 7,
          fieldOrderGroup: 3,
          isActive: true,
          isUnique: false,
          fieldWidth: 'full',
          languageSlug: 'en',
          fieldGroup: 'correspondenceAddress',
          conditionalLogic: [
            {
              when: {
                field: 'correspondenceCountry',
                operator: 'equal',
                value: 'India',
              },
              then: {
                fieldType: 'dropdown',
                fieldPlaceholder: 'Select district',
                validationRules: {
                  required: true,
                  requiredMessage: 'Select district',
                  maxLength: '50',
                  maxLengthMessage: 'Max length for district is 50',
                },
              },
              else: {
                fieldType: 'textfield',
                fieldPlaceholder: 'Enter district',
                validationRules: {
                  required: false,
                  requiredMessage: 'Enter district',
                  maxLength: '50',
                  maxLengthMessage: 'Max length for district is 50',
                },
              },
            },
          ],
          fieldAttributes: {
            type: 'external_api',
            trigger: 'blur',
            url: `${CMS_URL}/api/masters/district/{correspondenceState}/formatted`,
            urlData: 'correspondenceState',
            method: 'GET',
            responseMapping: {
              label: 'name',
              value: 'name',
            },
          },
        },
        {
          id: 213,
          formType: 'RE_addressDetails',
          fieldName: 'correspondenceCity',
          fieldLabel: 'City/Town',
          fieldType: 'textfield',
          fieldPlaceholder: 'Enter city',
          fieldOptions: [],
          validationRules: {},
          fieldOrder: 8,
          fieldOrderGroup: 3,
          isActive: true,
          isUnique: false,
          fieldWidth: 'full',
          languageSlug: 'en',
          fieldGroup: 'correspondenceAddress',
          conditionalLogic: [
            {
              when: {
                field: 'correspondenceCountry',
                operator: 'equal',
                value: 'India',
              },
              then: {
                fieldType: 'textfield',
                fieldPlaceholder: 'Enter city/town',
                validationRules: {
                  required: true,
                  requiredMessage: 'Enter city',
                  maxLength: '60',
                  maxLengthMessage: 'Max length for city is 60',
                  regx: '^[A-Za-z0-9]+( [A-Za-z0-9]+)*$',
                  regxMessage:
                    'City/Town must contain only alphanumeric characters with a single space between words.',
                },
              },
              else: {
                fieldType: 'textfield',
                fieldPlaceholder: 'Enter city/town',
                validationRules: {
                  required: false,
                  requiredMessage: 'Enter city',
                  maxLength: '50',
                  maxLengthMessage: 'Max length for city is 50',
                  regx: '^[A-Za-z0-9]+( [A-Za-z0-9]+)*$',
                  regxMessage:
                    'City/Town must contain only alphanumeric characters with a single space between words.',
                },
              },
            },
          ],
        },
        {
          id: 214,
          formType: 'RE_addressDetails',
          fieldName: 'correspondencePincode',
          fieldLabel: 'Pin Code',
          fieldType: 'dropdown',
          fieldPlaceholder: 'Select pin code',
          fieldOptions: [],
          validationRules: {},
          fieldOrder: 9,
          fieldOrderGroup: 3,
          isActive: true,
          isUnique: false,
          fieldWidth: 'full',
          languageSlug: 'en',
          fieldGroup: 'correspondenceAddress',
          conditionalLogic: [
            {
              when: {
                field: 'correspondenceCountry',
                operator: 'equal',
                value: 'India',
              },
              then: {
                fieldType: 'dropdown',
                fieldPlaceholder: 'Select pin code',
                validationRules: {
                  required: true,
                  requiredMessage: 'Select PIN CODE',
                  maxLength: '6',
                  maxLengthMessage: 'Max length for pincode is 6',
                  minLength: '6',
                  minLengthMessage: 'Min length for pincode is 6',
                  numberValudation: true,
                },
              },
              else: {
                fieldType: 'textfield',
                fieldPlaceholder: 'Enter pin code',
                validationRules: {
                  required: false,
                  requiredMessage: 'Enter PIN CODE',
                  maxLength: '50',
                  maxLengthMessage: 'Max length for pincode is 50',
                  numberValudation: false,
                  regx: '^[A-Za-z0-9]+$',
                  regxMessage: 'PIN code can contain only letters and numbers.',
                },
              },
            },
          ],
          fieldAttributes: {
            type: 'external_api',
            trigger: 'blur',
            url: `${CMS_URL}/api/masters/pincode/{correspondenceDistrict}/formatted`,
            urlData: 'correspondenceDistrict',
            method: 'GET',
            responseMapping: {
              label: 'pincode',
              value: 'pincode',
            },
          },
        },
        {
          id: 215,
          formType: 'RE_addressDetails',
          fieldName: 'correspondencePincodeOther',
          fieldLabel: 'Pin Code (in case of others)',
          fieldType: 'textfield',
          fieldPlaceholder: 'Enter other pin code',
          fieldOptions: [],
          validationRules: {},
          fieldOrder: 10,
          fieldOrderGroup: 3,
          isActive: true,
          isUnique: false,
          fieldWidth: 'full',
          languageSlug: 'en',
          fieldGroup: 'correspondenceAddress',
          conditionalLogic: [
            {
              when: {
                field: 'correspondencePincode',
                operator: 'is',
                value: 'other',
              },
              then: {
                validationRules: {
                  required: true,
                  requiredMessage: 'Enter PIN CODE',
                  maxLength: '6',
                  maxLengthMessage: 'Max length for pincode is 6',
                  minLength: '6',
                  minLengthMessage: 'Min length for pincode is 6',
                  numberValudation: true,
                },
              },
              else: {
                validationRules: {
                  required: false,
                  requiredMessage: 'Enter PIN CODE',
                  maxLength: '50',
                  maxLengthMessage: 'Max length for pincode is 50',
                  numberValudation: true,
                },
              },
            },
          ],
        },
        {
          id: 216,
          formType: 'RE_addressDetails',
          fieldName: 'correspondenceDigipin',
          fieldLabel: 'Digipin',
          fieldType: 'textfield',
          fieldPlaceholder: 'Enter your digipin',
          fieldOptions: [],
          validationRules: {
            required: false,
            maxLength: '12',
            maxLengthMessage: 'Max length for digipin is 12',
            regx: '^[2-9CFJKLMPT]{3}-[2-9CFJKLMPT]{3}-[2-9CFJKLMPT]{4}$',
            regxMessage:
              'Please enter a valid Digipin (eg: 29C-45F-7JMT). Only digits 2-9 and letters C,F,J,K,L,M,P,T are allowed.',
          },
          fieldOrder: 11,
          fieldOrderGroup: 3,
          isActive: true,
          isUnique: false,
          fieldWidth: 'full',
          languageSlug: 'en',
          fieldGroup: 'correspondenceAddress',
        },
      ],
    },
  },
  configuration: {
    id: 4,
    formType: 'RE_addressDetails',
    formTitle: 'Address Details',
    formSubtitle: 'Address Details',
    formDescription: 'Fill out this form',
    formSettings: {
      formGroup: true,
      showProgress: false,
      enablecaptcha: false,
      isMultiSteps: true,
      stepsData: {
        nextStep: 'RE_hoi',
        previousStep: 'RE_entityProfile',
        currentStep: 'RE_addressDetails',
      },
    },
    submissionSettings: {
      clearButton: true,
      clearButtonText: 'Clear',
      submitButton: true,
      submitButtonText: 'Save and Next',
      validateIsGroup: false,
      validateButton: false,
    },
    isActive: true,
    languageSlug: 'en',
    formLayout: 'single-column',
    formTheme: 'modern',
    allowMultipleSubmissions: true,
    requiresAuthentication: false,
    parentId: 1,
  },
};

