// Frontend Form Configuration for Admin User Details Step (Stepper 5)
// This replaces the API call to GET /api/forms/RE_iau/fields?is_group=true

import { FrontendFormConfig } from '../types/configTypes';

// Helper function to create admin fields (reusable for adminOne and adminTwo)
const createAdminFields = (adminNumber: 1 | 2) => {
  const suffix = adminNumber.toString();
  return [
    {
      id: adminNumber === 1 ? 254 : 272,
      formType: 'RE_iau',
      fieldName: `iauCitizenship${suffix}`,
      fieldLabel: 'Citizenship',
      fieldType: 'dropdown',
      fieldPlaceholder: 'Select Citizenship',
      fieldMaster: 'citizenship',
      validationRules: {
        required: true,
        requiredMessage: 'Please select citizenship',
      },
      fieldOrder: 1,
      fieldOrderGroup: adminNumber === 1 ? 6 : 7,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
      fieldGroup: `admin${adminNumber === 1 ? 'One' : 'Two'}`,
    },
    {
      id: adminNumber === 1 ? 255 : 273,
      formType: 'RE_iau',
      fieldName: `iauCkycNumber${suffix}`,
      fieldLabel: 'CKYC Number',
      fieldType: 'textfield_with_verify',
      fieldPlaceholder: null,
      fieldOptions: [],
      validationRules: undefined,
      fieldOrder: 2,
      fieldOrderGroup: adminNumber === 1 ? 6 : 7,
      isActive: true,
      isUnique: true,
      fieldWidth: 'full',
      languageSlug: 'en',
      fieldGroup: `admin${adminNumber === 1 ? 'One' : 'Two'}`,
      conditionalLogic: [
        {
          when: {
            field: `iauCitizenship${suffix}`,
            operator: 'equals',
            value: 'Indian',
          },
          then: {
            validationRules: {
              required: true,
              requiredMessage: 'Please enter the CKYC number as Citizenship is India.',
              maxLength: '14',
              maxLengthMessage: 'CKYC number must be exactly 14 characters long.',
              minLength: '14',
              minLengthMessage: 'CKYC number must be exactly 14 characters long.',
              regx: '^[0-9]{14}$',
              regxMessage: 'CKYC number must contain only 14 digits.',
            },
            fieldAttributes: {
              type: 'external_api',
              trigger: 'blur',
              url: 'https://dev.ckycindia.dev/re/api/v1/otp/ckyc-verify',
              method: 'POST',
              urlData: 'ckyc_number',
              responseMapping: {
                label: 'name',
                value: 'name',
              },
              description: 'Hit API when click in Verify CKYC button and citizenship selected is India',
              autoPopulate: [
                `iauTitle${suffix}`,
                `iauFirstName${suffix}`,
                `iauLastName${suffix}`,
                `iauMiddleName${suffix}`,
                `iauCkycNumber${suffix}`,
                `iauGender${suffix}`,
              ],
            },
          },
        },
      ],
    },
    {
      id: adminNumber === 1 ? 256 : 274,
      formType: 'RE_iau',
      fieldName: `iauTitle${suffix}`,
      fieldLabel: 'Title',
      fieldType: 'dropdown',
      fieldPlaceholder: null,
      fieldMaster: 'titles',
      validationRules: {
        required: true,
        requiredMessage: 'Please select a title (Mr./Mrs./Ms.).',
      },
      fieldOrder: 3,
      fieldOrderGroup: adminNumber === 1 ? 6 : 7,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
      fieldGroup: `admin${adminNumber === 1 ? 'One' : 'Two'}`,
    },
    {
      id: adminNumber === 1 ? 257 : 275,
      formType: 'RE_iau',
      fieldName: `iauFirstName${suffix}`,
      fieldLabel: 'First Name',
      fieldType: 'textfield',
      fieldPlaceholder: 'Enter first name',
      fieldOptions: [],
      validationRules: {
        required: true,
        requiredMessage: 'Enter first name.',
        regx: "^(?!.*'.*')[A-Za-z .']+$",
        regxMessage: 'First Name can only contain letters, spaces, single apostrophes, dots.',
        maxLength: '33',
        maxLengthMessage: 'First Name cannot exceed 33 characters.',
        minLength: '2',
        minLengthMessage: 'First Name must be at least 2 characters.',
      },
      fieldOrder: 4,
      fieldOrderGroup: adminNumber === 1 ? 6 : 7,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
      fieldGroup: `admin${adminNumber === 1 ? 'One' : 'Two'}`,
    },
    {
      id: adminNumber === 1 ? 258 : (adminNumber === 2 ? 1324 : 276),
      formType: 'RE_iau',
      fieldName: `iauMiddleName${suffix}`,
      fieldLabel: 'Middle Name',
      fieldType: 'textfield',
      fieldPlaceholder: 'Enter Middle Name',
      fieldOptions: [],
      validationRules: {
        required: false,
        regx: "^(?!.*'.*')[A-Za-z .']+$",
        regxMessage: 'Middle Name can only contain letters, spaces, single apostrophes, dots.',
        maxLength: '33',
        maxLengthMessage: 'Middle Name cannot exceed 33 characters.',
      },
      fieldOrder: 5,
      fieldOrderGroup: adminNumber === 1 ? 6 : 7,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
      fieldGroup: `admin${adminNumber === 1 ? 'One' : 'Two'}`,
    },
    {
      id: adminNumber === 1 ? 259 : 277,
      formType: 'RE_iau',
      fieldName: `iauLastName${suffix}`,
      fieldLabel: 'Last Name',
      fieldType: 'textfield',
      fieldPlaceholder: 'Enter Last Name',
      fieldOptions: [],
      validationRules: {
        required: false,
        regx: "^(?!.*'.*')[A-Za-z .']+$",
        regxMessage: 'Last Name can only contain letters, spaces, single apostrophes, dots.',
        maxLength: '33',
        maxLengthMessage: 'Last Name cannot exceed 33 characters.',
        minLength: '2',
        minLengthMessage: 'Last Name must be at least 2 characters.',
      },
      fieldOrder: 6,
      fieldOrderGroup: adminNumber === 1 ? 6 : 7,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
      fieldGroup: `admin${adminNumber === 1 ? 'One' : 'Two'}`,
    },
    {
      id: adminNumber === 1 ? 260 : 278,
      formType: 'RE_iau',
      fieldName: `iauGender${suffix}`,
      fieldLabel: 'Gender',
      fieldType: 'dropdown',
      fieldPlaceholder: 'Select Gender',
      fieldMaster: 'gender',
      validationRules: {
        required: true,
        requiredMessage: 'Select gender.',
      },
      fieldOrder: 7,
      fieldOrderGroup: adminNumber === 1 ? 6 : 7,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
      fieldGroup: `admin${adminNumber === 1 ? 'One' : 'Two'}`,
    },
    {
      id: adminNumber === 1 ? 261 : 279,
      formType: 'RE_iau',
      fieldName: `iauDob${suffix}`,
      fieldLabel: 'Date of Birth',
      fieldType: 'date',
      fieldPlaceholder: null,
      fieldOptions: [],
      validationRules: {
        required: true,
        requiredMessage: 'Select your DOB',
        isAdultAge: '18',
        maxDate: 'true',
      },
      fieldOrder: 8,
      fieldOrderGroup: adminNumber === 1 ? 6 : 7,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
      fieldGroup: `admin${adminNumber === 1 ? 'One' : 'Two'}`,
    },
    {
      id: adminNumber === 1 ? 262 : 280,
      formType: 'RE_iau',
      fieldName: `iauDesignation${suffix}`,
      fieldLabel: 'Designation',
      fieldType: 'textfield',
      fieldPlaceholder: 'Enter designation',
      fieldOptions: [],
      validationRules: {
        required: true,
        requiredMessage: 'Enter designation',
        maxLength: '100',
        maxLengthMessage: 'Designation cannot exceed 100 characters.',
        regx: '^[A-Za-z0-9`~@#$%^&*()_+\\-=]+( [A-Za-z0-9`~@#$%^&*()_+\\-=]+)*$',
        regxMessage:
          'Designation can only contain alphanumeric characters and the symbols `~@#$%^&*()_+-= with single spaces between words only.',
      },
      fieldOrder: 9,
      fieldOrderGroup: adminNumber === 1 ? 6 : 7,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
      fieldGroup: `admin${adminNumber === 1 ? 'One' : 'Two'}`,
    },
    {
      id: adminNumber === 1 ? 85 : 281,
      formType: 'RE_iau',
      fieldName: `iauEmployCode${suffix}`,
      fieldLabel: 'Employee Code',
      fieldFileName: `iauEmployCode${suffix}File`,
      fieldType: 'textfield_with_image',
      fieldPlaceholder: 'Enter employee code',
      fieldOptions: [],
      validationRules: {
        required: true,
        requiredMessage: 'Employee Code is required',
        regx: '^[A-Za-z0-9+]{0,50}$',
        regxMessage: 'Employee code must be alphanumeric with + allowed.',
        maxLength: '20',
        maxLengthMessage: 'Employee code cannot exceed more then 20',
        validationFile: {
          imageFormat: ['jpeg', 'pdf', 'jpg'],
          imageRequired: true,
          imageRequiredMessage: 'Please upload image',
          size: '500kb',
          sizeMessage: 'Image not more then 500KB',
        },
      },
      fieldOrder: 10,
      fieldOrderGroup: adminNumber === 1 ? 6 : 7,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
      fieldGroup: `admin${adminNumber === 1 ? 'One' : 'Two'}`,
    },
    {
      id: adminNumber === 1 ? 263 : 282,
      formType: 'RE_iau',
      fieldName: `iauEmail${suffix}`,
      fieldLabel: 'Email',
      fieldType: 'textfield',
      fieldPlaceholder: 'Enter email',
      fieldOptions: [],
      validationRules: {
        required: true,
        requiredMessage: 'Enter your email address.',
        maxLength: '254',
        maxLengthMessage: 'Email address cannot exceed 254 characters.',
        regx: '^(?=.*@)[A-Za-z0-9`~@#$%^&*.()_+\\-=]+$',
        regxMessage: 'Enter a valid email address format.',
      },
      fieldOrder: 11,
      fieldOrderGroup: adminNumber === 1 ? 6 : 7,
      isActive: true,
      isUnique: true,
      fieldWidth: 'full',
      languageSlug: 'en',
      fieldGroup: `admin${adminNumber === 1 ? 'One' : 'Two'}`,
    },
    {
      id: adminNumber === 1 ? 264 : 283,
      formType: 'RE_iau',
      fieldName: `iauCountryCode${suffix}`,
      fieldLabel: 'Country Code',
      fieldType: 'dropdown',
      fieldPlaceholder: 'Select country code',
      fieldMaster: 'countryCode',
      validationRules: {
        required: true,
        requiredMessage: 'Select a country code.',
        maxLength: '10',
        maxLengthMessage: 'Valid length for country code is 10',
      },
      fieldOrder: 12,
      fieldOrderGroup: adminNumber === 1 ? 6 : 7,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
      fieldGroup: `admin${adminNumber === 1 ? 'One' : 'Two'}`,
    },
    {
      id: adminNumber === 1 ? 265 : 284,
      formType: 'RE_iau',
      fieldName: `iauMobileNumber${suffix}`,
      fieldLabel: 'Mobile Number',
      fieldType: 'textfield',
      fieldPlaceholder: null,
      fieldOptions: [],
      validationRules: undefined,
      fieldOrder: 13,
      fieldOrderGroup: adminNumber === 1 ? 6 : 7,
      isActive: true,
      isUnique: true,
      fieldWidth: 'full',
      languageSlug: 'en',
      fieldGroup: `admin${adminNumber === 1 ? 'One' : 'Two'}`,
      conditionalLogic: [
        {
          when: {
            field: `iauCountryCode${suffix}`,
            operator: 'in',
            value: ['+91'],
          },
          then: {
            validationRules: {
              required: true,
              requiredMessage: 'Mobile number is required for Indian citizens.',
              maxLength: '10',
              maxLengthMessage: 'Mobile number must be 10 digits for Indian citizens.',
              minLength: '10',
              minLengthMessage: 'Mobile number must be 10 digits for Indian citizens.',
              numberValudation: true,
              regx: '^[0-9]{10}$',
              regxMessage: 'Mobile number must be 10 digits only.',
            },
          },
          else: {
            validationRules: {
              required: true,
              requiredMessage: 'Mobile number is required.',
              maxLength: '15',
              maxLengthMessage: 'Mobile number cannot exceed 15 digits.',
              minLength: '8',
              minLengthMessage: 'Mobile number must be at least 8 digits.',
              numberValudation: true,
              regx: '^[0-9]+$',
              regxMessage: 'Mobile number must contain only digits.',
            },
          },
        },
      ],
    },
    {
      id: adminNumber === 1 ? 266 : 285,
      formType: 'RE_iau',
      fieldName: `iauLandlineNumber${suffix}`,
      fieldLabel: 'Landline Number',
      fieldType: 'textfield',
      fieldPlaceholder: 'Enter landline number',
      fieldOptions: [],
      validationRules: {
        required: false,
        regx: '^[A-Za-z0-9+]+$',
        regxMessage: 'Landline number can contain letters, numbers, and + sign only.',
        maxLength: '15',
        maxLengthMessage: 'Landline number cannot exceed 15 digits.',
      },
      fieldOrder: 14,
      fieldOrderGroup: adminNumber === 1 ? 6 : 7,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
      fieldGroup: `admin${adminNumber === 1 ? 'One' : 'Two'}`,
    },
    {
      id: adminNumber === 1 ? 267 : 286,
      formType: 'RE_iau',
      fieldName: `iauOfficeAddress${suffix}`,
      fieldLabel: 'Office Address',
      fieldType: 'dropdown',
      fieldPlaceholder: 'Enter office address',
      fieldOptions: [
        {
          value: 'Same as registered address',
          label: 'Same as registered address',
        },
        {
          value: 'Same as correspondence address',
          label: 'Same as correspondence address',
        },
      ],
      validationRules: {
        required: true,
        requiredMessage: 'Please select office address',
      },
      fieldOrder: 15,
      fieldOrderGroup: adminNumber === 1 ? 6 : 7,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
      fieldGroup: `admin${adminNumber === 1 ? 'One' : 'Two'}`,
    },
    // Address fields for admin
    {
      id: adminNumber === 1 ? 1345 : 1355,
      formType: 'RE_iau',
      fieldName: `iauAddressLine${adminNumber === 1 ? 'One' : 'Two'}1`,
      fieldLabel: 'Address Line 1',
      fieldType: 'textfield',
      fieldPlaceholder: 'Add address here',
      fieldOptions: [],
      validationRules: {
        required: true,
        requiredMessage: 'Please enter address line 1',
      },
      fieldOrder: 16,
      fieldOrderGroup: adminNumber === 1 ? 6 : 7,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
      fieldGroup: `admin${adminNumber === 1 ? 'One' : 'Two'}`,
    },
    {
      id: adminNumber === 1 ? 1346 : 1356,
      formType: 'RE_iau',
      fieldName: `iauAddressLine${adminNumber === 1 ? 'One' : 'Two'}2`,
      fieldLabel: 'Address Line 2',
      fieldType: 'textfield',
      fieldPlaceholder: 'Add address here',
      fieldOptions: [],
      validationRules: {
        required: false,
      },
      fieldOrder: 17,
      fieldOrderGroup: adminNumber === 1 ? 6 : 7,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
      fieldGroup: `admin${adminNumber === 1 ? 'One' : 'Two'}`,
    },
    {
      id: adminNumber === 1 ? 1347 : 1357,
      formType: 'RE_iau',
      fieldName: `iauAddressLine${adminNumber === 1 ? 'One' : 'Two'}3`,
      fieldLabel: 'Address Line 3',
      fieldType: 'textfield',
      fieldPlaceholder: 'Add address here',
      fieldOptions: [],
      validationRules: {
        required: false,
      },
      fieldOrder: 18,
      fieldOrderGroup: adminNumber === 1 ? 6 : 7,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
      fieldGroup: `admin${adminNumber === 1 ? 'One' : 'Two'}`,
    },
    {
      id: adminNumber === 1 ? 1348 : 1358,
      formType: 'RE_iau',
      fieldName: `iauCountry${suffix}`,
      fieldLabel: 'Country',
      fieldType: 'dropdown',
      fieldPlaceholder: 'Select country',
      fieldMaster: 'countryCode',
      validationRules: {
        required: true,
        requiredMessage: 'Please select country',
        maxLength: '60',
        maxLengthMessage: 'Max length for country is 60',
      },
      fieldOrder: 19,
      fieldOrderGroup: adminNumber === 1 ? 6 : 7,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
      fieldGroup: `admin${adminNumber === 1 ? 'One' : 'Two'}`,
    },
    {
      id: adminNumber === 1 ? 1349 : 1359,
      formType: 'RE_iau',
      fieldName: `iauState${suffix}`,
      fieldLabel: 'State / UT',
      fieldType: 'textfield',
      fieldPlaceholder: 'Select state',
      fieldOptions: [],
      validationRules: {},
      fieldOrder: 20,
      fieldOrderGroup: adminNumber === 1 ? 6 : 7,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
      fieldGroup: `admin${adminNumber === 1 ? 'One' : 'Two'}`,
      conditionalLogic: [
        {
          when: {
            field: `iauCountry${suffix}`,
            operator: 'equal',
            value: 'India',
          },
          then: {
            validationRules: {
              required: true,
              requiredMessage: 'Select state',
              maxLength: '60',
              maxLengthMessage: 'Max length for state is 60',
            },
          },
          else: {
            validationRules: {
              required: false,
              requiredMessage: 'Enter state',
              maxLength: '60',
              maxLengthMessage: 'Max length for state is 60',
            },
          },
        },
      ],
      fieldAttributes: {
        type: 'external_api',
        trigger: 'blur',
        url: `https://dev.ckycindia.dev/cms/api/masters/state/{iauCountry${suffix}}/formatted`,
        method: 'GET',
        urlData: `iauCountry${suffix}`,
        responseMapping: {
          label: 'name',
          value: 'name',
        },
      },
    },
    {
      id: adminNumber === 1 ? 1350 : 1360,
      formType: 'RE_iau',
      fieldName: `iauDistrict${suffix}`,
      fieldLabel: 'District',
      fieldType: 'textfield',
      fieldPlaceholder: 'Select district',
      fieldOptions: [],
      validationRules: {},
      fieldOrder: 21,
      fieldOrderGroup: adminNumber === 1 ? 6 : 7,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
      fieldGroup: `admin${adminNumber === 1 ? 'One' : 'Two'}`,
      conditionalLogic: [
        {
          when: {
            field: `iauCountry${suffix}`,
            operator: 'equal',
            value: 'India',
          },
          then: {
            validationRules: {
              required: true,
              requiredMessage: 'Select district',
              maxLength: '40',
              maxLengthMessage: 'Max lengths for district is 40',
            },
          },
          else: {
            validationRules: {
              required: false,
              requiredMessage: 'Enter district',
              maxLength: '40',
              maxLengthMessage: 'Max lengths for district is 40',
            },
          },
        },
      ],
      fieldAttributes: {
        type: 'external_api',
        trigger: 'blur',
        url: `https://dev.ckycindia.dev/cms/api/masters/district/{iauState${suffix}}/formatted`,
        method: 'GET',
        urlData: `iauState${suffix}`,
        responseMapping: {
          label: 'name',
          value: 'name',
        },
      },
    },
    {
      id: adminNumber === 1 ? 1351 : 1361,
      formType: 'RE_iau',
      fieldName: `iauCity${suffix}`,
      fieldLabel: 'City / Town',
      fieldType: 'textfield',
      fieldPlaceholder: 'Enter city/town',
      fieldOptions: [],
      validationRules: {},
      fieldOrder: 22,
      fieldOrderGroup: adminNumber === 1 ? 6 : 7,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
      fieldGroup: `admin${adminNumber === 1 ? 'One' : 'Two'}`,
      conditionalLogic: [
        {
          when: {
            field: `iauCountry${suffix}`,
            operator: 'equal',
            value: 'India',
          },
          then: {
            validationRules: {
              required: true,
              requiredMessage: 'Enter city',
              maxLength: '60',
              maxLengthMessage: 'Max length for district is 60',
            },
          },
          else: {
            validationRules: {
              required: false,
              requiredMessage: 'Select city',
              maxLength: '60',
              maxLengthMessage: 'Max length for district is 60',
            },
          },
        },
      ],
    },
    {
      id: adminNumber === 1 ? 1352 : 1362,
      formType: 'RE_iau',
      fieldName: `iauPincode${suffix}`,
      fieldLabel: 'Pin Code',
      fieldType: 'textfield',
      fieldPlaceholder: 'Enter pin code',
      fieldOptions: [],
      validationRules: {},
      fieldOrder: 23,
      fieldOrderGroup: adminNumber === 1 ? 6 : 7,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
      fieldGroup: `admin${adminNumber === 1 ? 'One' : 'Two'}`,
      conditionalLogic: [
        {
          when: {
            field: `iauCountry${suffix}`,
            operator: 'equal',
            value: 'India',
          },
          then: {
            validationRules: {
              required: true,
              requiredMessage: 'Select pin code',
              maxLength: '6',
              maxLengthMessage: 'Max length for district is 6',
            },
          },
          else: {
            validationRules: {
              required: false,
              requiredMessage: 'Enter pin code',
              maxLength: '6',
              maxLengthMessage: 'Max length for district is 6',
            },
          },
        },
      ],
      fieldAttributes: {
        type: 'external_api',
        trigger: 'blur',
        url: `https://dev.ckycindia.dev/cms/api/masters/pincode/{iauDistrict${suffix}}/formatted`,
        method: 'GET',
        urlData: `iauDistrict${suffix}`,
        responseMapping: {
          label: 'name',
          value: 'name',
        },
      },
    },
    {
      id: adminNumber === 1 ? 1353 : 1363,
      formType: 'RE_iau',
      fieldName: `iauPincodeOther${suffix}`,
      fieldLabel: 'Pin Code (in case of others)',
      fieldType: 'textfield',
      fieldPlaceholder: 'Enter pin code',
      fieldOptions: [],
      validationRules: undefined,
      fieldOrder: 24,
      fieldOrderGroup: adminNumber === 1 ? 6 : 7,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
      fieldGroup: `admin${adminNumber === 1 ? 'One' : 'Two'}`,
      conditionalLogic: [
        {
          when: {
            field: 'register_pincode',
            operator: 'is',
            value: 'other',
          },
          then: {
            validationRules: {
              required: true,
              requiredMessage: 'Enter pin code',
              maxLength: '6',
              maxLengthMessage: 'Max length for district is 6',
            },
          },
          else: {
            validationRules: {
              required: false,
              requiredMessage: 'Enter pin code',
              maxLength: '6',
              maxLengthMessage: 'Max length for district is 6',
            },
          },
        },
      ],
    },
    {
      id: adminNumber === 1 ? 1354 : 1364,
      formType: 'RE_iau',
      fieldName: `iauDigipin${suffix}`,
      fieldLabel: 'Digipin',
      fieldType: 'textfield',
      fieldPlaceholder: 'Enter your digipin',
      fieldOptions: [],
      validationRules: {
        required: false,
        maxLength: '12',
        maxLengthMessage: 'Max length for digipin is 12',
        regx: '^[2-9CFJKLMPT]{3}-[2-9CFJKLMPT]{3}-[2-9CFJKLMPT]{4}$',
        regxMessage:
          'Please enter a valid Digipin (eg: 29C-45F-7JMT). Only digits 2-9 and letters C,F,J,K,L,M,P,T are allowed.',
      },
      fieldOrder: 25,
      fieldOrderGroup: adminNumber === 1 ? 6 : 7,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
      fieldGroup: `admin${adminNumber === 1 ? 'One' : 'Two'}`,
    },
    {
      id: adminNumber === 1 ? 268 : 287,
      formType: 'RE_iau',
      fieldName: `iauProofOfIdentity${suffix}`,
      fieldLabel: 'Proof of Identity',
      fieldType: 'dropdown',
      fieldPlaceholder: '',
      fieldMaster: 'proofOfIdentities',
      validationRules: {
        required: true,
        requiredMessage: 'Please select proof of identity',
      },
      fieldOrder: 26,
      fieldOrderGroup: adminNumber === 1 ? 6 : 7,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
      fieldGroup: `admin${adminNumber === 1 ? 'One' : 'Two'}`,
    },
    {
      id: adminNumber === 1 ? 269 : 288,
      formType: 'RE_iau',
      fieldName: `iauProofOfIdentityNumber${suffix}`,
      fieldLabel: 'Proof of Indentity Number',
      fieldFileName: `iauProofOfIdentityNumber${suffix}File`,
      fieldType: 'textfield_with_image',
      fieldPlaceholder: 'Enter number',
      fieldOptions: [],
      validationRules: {
        required: true,
        requiredMessage: 'Proof of identity number is required',
        maxLength: '50',
        maxLengthMessage: 'Proof of identity number is not more then 50 character',
        validationFile: {
          imageFormat: ['jpeg', 'pdf', 'jpg'],
          imageRequired: true,
          imageRequiredMessage: 'Please upload image',
          size: '500kb',
          sizeMessage: 'Image not more then 500KB',
        },
      },
      fieldOrder: 27,
      fieldOrderGroup: adminNumber === 1 ? 6 : 7,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
      fieldGroup: `admin${adminNumber === 1 ? 'One' : 'Two'}`,
    },
    {
      id: adminNumber === 1 ? 270 : 289,
      formType: 'RE_iau',
      fieldName: `iauDateOfAuthorization${suffix}`,
      fieldLabel: 'Date of Authorization',
      fieldType: 'date',
      fieldPlaceholder: '',
      fieldOptions: [],
      validationRules: {
        required: true,
        requiredMessage: 'Please select date of authorization',
        maxDate: 'true',
      },
      fieldOrder: 28,
      fieldOrderGroup: adminNumber === 1 ? 6 : 7,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
      fieldGroup: `admin${adminNumber === 1 ? 'One' : 'Two'}`,
    },
    {
      id: adminNumber === 1 ? 271 : 290,
      formType: 'RE_iau',
      fieldName: `iauAuthorizationLetter${suffix}`,
      fieldLabel: 'Authorization letter by Competent Authority',
      fieldFileName: `iauAuthorizationLetter${suffix}File`,
      fieldType: 'textfield_with_image',
      fieldPlaceholder: 'Enter here',
      fieldOptions: [],
      validationRules: {
        required: true,
        requiredMessage: 'Authorization letter is required',
        regx: '^[A-Za-z0-9+ ]{1,20}$',
        regxMessage:
          'Authorization letter can contain alphanumeric characters and "+" only, max 20 characters.',
        maxLength: '20',
        maxLengthMessage: 'Authorization letter cannot exceed 20 characters.',
        validationFile: {
          imageFormat: ['jpeg', 'pdf', 'jpg'],
          imageRequired: true,
          imageRequiredMessage: 'Please upload image',
          size: '500kb',
          sizeMessage: 'Image not more then 500KB',
        },
      },
      fieldOrder: 29,
      fieldOrderGroup: adminNumber === 1 ? 6 : 7,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
      fieldGroup: `admin${adminNumber === 1 ? 'One' : 'Two'}`,
    },
  ];
};

export const adminUserDetailsConfig: FrontendFormConfig = {
  formType: 'RE_iau',
  fields: [],
  groupedFields: {
    adminone: {
      label: 'Admin One',
      fields: createAdminFields(1) as any,
    },
    admintwo: {
      label: 'Admin Two',
      fields: createAdminFields(2) as any,
    },
  },
  configuration: {
    id: 7,
    formType: 'RE_iau',
    formTitle: 'Institutional Admin User Details',
    formSubtitle: 'Institutional Admin User Details',
    formDescription: 'Fill out this form',
    formSettings: {
      formGroup: true,
      showProgress: false,
      enablecaptcha: false,
      isMultiSteps: true,
      stepsData: {
        nextStep: 'RE_formPreview',
        previousStep: 'RE_nodal',
        currentStep: 'RE_iau',
      },
    },
    submissionSettings: {
      clearButton: false,
      submitButton: true,
      submitButtonText: 'Save and Next',
      validateIsGroup: true,
      validateGroupButtons: [
        {
          validateButton: true,
          validateButtonText: 'Validate Admin 1',
        },
        {
          validateButton: true,
          validateButtonText: 'Validate Admin 2',
        },
      ],
    },
    isActive: true,
    languageSlug: 'en',
    formLayout: 'single-column',
    formTheme: 'modern',
    allowMultipleSubmissions: true,
    requiresAuthentication: false,
    parentId: 1,
  },
};

