// Frontend Form Configuration for Entity Profile Step
// This replaces the API call to GET /api/forms/RE_entityProfile/fields?is_group=true

import { FrontendFormConfig } from '../types/configTypes';

export const entityProfileConfig: FrontendFormConfig = {
  formType: 'RE_entityProfile',
  fields: [
    {
      id: 10,
      formType: 'RE_entityProfile',
      fieldName: 'nameOfInstitution',
      fieldLabel: 'Name of Institution',
      fieldType: 'textfield',
      fieldPlaceholder: 'Enter name of institution',
      validationRules: {
        required: true,
        requiredMessage: 'Please enter the name of the institution.',
        maxLength: '99',
        maxLengthMessage: 'Name of Institution cannot exceed 99 characters.',
        regx: '^[A-Za-z0-9`~!@#$%^&*()_.+\\-= ]+$',
        regxMessage: 'Only letters, numbers, spaces, and allowed special characters (`~!@#$%^&*()_.+-=) are permitted.',
      },
      fieldOrder: 1,
      fieldOrderGroup: 0,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
    },
    {
      id: 11,
      formType: 'RE_entityProfile',
      fieldName: 'regulator',
      fieldLabel: 'Regulator',
      fieldType: 'dropdown',
      fieldPlaceholder: 'Select Regulator',
      fieldMaster: 'regulators', // Will be fetched from API
      validationRules: {
        required: true,
        requiredMessage: 'Please select the regulator.',
      },
      fieldOrder: 2,
      fieldOrderGroup: 0,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
    },
    {
      id: 12,
      formType: 'RE_entityProfile',
      fieldName: 'institutionType',
      fieldLabel: 'Institution Type',
      fieldType: 'dropdown',
      fieldPlaceholder: 'Select Institution Type',
      fieldMaster: 'institutionTypes', // Will be fetched from API
      validationRules: {
        required: true,
        requiredMessage: 'Please select the institution type.',
      },
      fieldOrder: 3,
      fieldOrderGroup: 0,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
    },
    {
      id: 13,
      formType: 'RE_entityProfile',
      fieldName: 'constitution',
      fieldLabel: 'Constitution',
      fieldType: 'dropdown',
      fieldPlaceholder: 'Select Constitution',
      fieldMaster: 'constitutions', // Will be fetched from API
      validationRules: {
        required: true,
        requiredMessage: 'Please select the constitution type.',
      },
      fieldOrder: 4,
      fieldOrderGroup: 0,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
    },
    {
      id: 115,
      formType: 'RE_entityProfile',
      fieldName: 'proprietorName',
      fieldLabel: 'Proprietor Name',
      fieldType: 'textfield',
      fieldPlaceholder: 'Enter proprietor name',
      fieldOrder: 5,
      fieldOrderGroup: 0,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
      conditionalLogic: [
        {
          when: {
            field: 'constitution',
            operator: 'in',
            value: ['A'],
          },
          then: {
            validationRules: {
              required: true,
              requiredMessage: 'Proprietor Name is required.',
              maxLength: '50',
              maxLengthMessage: 'Proprietor Name cannot exceed 50 characters.',
              regx: '^[A-Za-z0-9 ]+$',
              regxMessage: 'Only alphabets, numbers, and spaces are allowed. Special characters are not permitted.',
            },
          },
          else: {
            validationRules: {
              required: false,
              requiredMessage: 'Proprietor Name is required.',
              maxLength: '50',
              maxLengthMessage: 'Proprietor Name cannot exceed 50 characters.',
              regx: '^[A-Za-z0-9 ]+$',
              regxMessage: 'Only alphabets, numbers, and spaces are allowed. Special characters are not permitted.',
            },
          },
        },
      ],
    },
    {
      id: 116,
      formType: 'RE_entityProfile',
      fieldName: 'regulatorLicenseNumber',
      fieldLabel: 'Regulator License/ Certificate',
      fieldFileName: 'regulatorLicenseNumberFile',
      fieldType: 'textfield_with_image',
      fieldPlaceholder: 'Enter registration number',
      validationRules: {
        required: true,
        requiredMessage: 'Registration Number is required',
        regx: '^(?=.*[A-Za-z0-9]).+$',
        regxMessage: 'Registration Number must contain alphanumeric characters and may include special characters.',
        maxLength: '50',
        maxLengthMessage: 'Registration Number cannot exceed 50 characters.',
        validationFile: {
          imageFormat: ['jpeg', 'pdf', 'jpg'],
          imageRequired: true,
          imageRequiredMessage: 'Please upload Registration number image.',
          size: '500kb',
          sizeMessage: 'Image size must not exceed 500KB.',
        },
      },
      fieldOrder: 6,
      fieldOrderGroup: 0,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
    },
    {
      id: 117,
      formType: 'RE_entityProfile',
      fieldName: 'pan',
      fieldLabel: 'PAN',
      fieldFileName: 'panFile',
      fieldType: 'textfield_with_image',
      fieldPlaceholder: 'Enter PAN number',
      validationRules: {
        required: true,
        requiredMessage: 'PAN number is required.',
        regx: '^[A-Z]{5}[0-9]{4}[A-Z]{1}$',
        regxMessage: 'PAN must be in the format AAAAA9999A.',
        maxLength: '10',
        maxLengthMessage: 'PAN must be 10 characters long.',
        minLength: '10',
        minLengthMessage: 'PAN must be 10 characters long.',
        validationFile: {
          imageFormat: ['jpeg', 'pdf', 'jpg'],
          imageRequired: true,
          imageRequiredMessage: 'Please upload PAN image.',
          size: '500kb',
          sizeMessage: 'Image size must not exceed 500KB.',
        },
      },
      fieldOrder: 7,
      fieldOrderGroup: 0,
      isActive: true,
      isUnique: true,
      fieldWidth: 'full',
      languageSlug: 'en',
    },
    {
      id: 118,
      formType: 'RE_entityProfile',
      fieldName: 'cin',
      fieldLabel: 'CIN',
      fieldFileName: 'cinFile',
      fieldType: 'textfield_with_image',
      fieldPlaceholder: 'Enter CIN',
      fieldOrder: 8,
      fieldOrderGroup: 0,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
      conditionalLogic: [
        {
          when: {
            field: 'constitution',
            operator: 'in',
            value: ['D', 'E', 'M'],
          },
          then: {
            validationRules: {
              required: true,
              requiredMessage: 'CIN is required.',
              regx: '^[LPUF]{1}[0-9]{5}[A-Z]{2}[0-9]{4}[A-Z]{3}[0-9]{6}$',
              regxMessage: 'CIN must be 21 characters and match the structural format (e.g., L12345MH2020PLC987654).',
              maxLength: '21',
              maxLengthMessage: 'CIN must be 21 characters long.',
              minLength: '21',
              minLengthMessage: 'CIN must be 21 characters long.',
              validationFile: {
                imageFormat: ['jpeg', 'jpg', 'pdf'],
                imageRequired: true,
                imageRequiredMessage: 'Please upload CIN image.',
                size: '500kb',
                sizeMessage: 'Image size must not exceed 500KB.',
              },
            },
          },
          else: {
            validationRules: {
              required: false,
              requiredMessage: 'CIN is required.',
              regx: '^[LPUF]{1}[0-9]{5}[A-Z]{2}[0-9]{4}[A-Z]{3}[0-9]{6}$',
              regxMessage: 'CIN must be 21 characters and match the structural format (e.g., L12345MH2020PLC987654).',
              maxLength: '21',
              maxLengthMessage: 'CIN must be 21 characters long.',
              minLength: '21',
              minLengthMessage: 'CIN must be 21 characters long.',
              validationFile: {
                imageFormat: ['jpeg', 'jpg', 'pdf'],
                imageRequired: false,
                imageRequiredMessage: 'Please upload CIN image.',
                size: '500kb',
                sizeMessage: 'Image size must not exceed 500KB.',
              },
            },
          },
        },
      ],
    },
    {
      id: 119,
      formType: 'RE_entityProfile',
      fieldName: 'llpin',
      fieldLabel: 'LLPIN (Limited liability Partnership firm)',
      fieldFileName: 'llpinFile',
      fieldType: 'textfield_with_image',
      fieldPlaceholder: 'Enter LLPIN',
      fieldOrder: 9,
      fieldOrderGroup: 0,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
      conditionalLogic: [
        {
          when: {
            field: 'constitution',
            operator: 'in',
            value: ['J'],
          },
          then: {
            validationRules: {
              required: true,
              requiredMessage: 'LLPIN is required when Constitution is LLP.',
              maxLength: '7',
              maxLengthMessage: 'LLPIN cannot exceed 7 characters.',
              regx: '^[A-Za-z0-9]{7}$',
              regxMessage: 'LLPIN must be 7 alphanumeric characters.',
              validationFile: {
                imageFormat: ['jpeg', 'pdf', 'jpg'],
                imageRequired: true,
                imageRequiredMessage: 'Please upload LLPIN image.',
                size: '500kb',
                sizeMessage: 'Image size must not exceed 500KB.',
              },
            },
          },
          else: {
            validationRules: {
              required: false,
              requiredMessage: 'LLPIN is required when Constitution is LLP.',
              maxLength: '7',
              maxLengthMessage: 'LLPIN cannot exceed 7 characters.',
              regx: '^[A-Za-z0-9]{7}$',
              regxMessage: 'LLPIN must be 7 alphanumeric characters.',
              validationFile: {
                imageFormat: ['jpeg', 'pdf', 'jpg'],
                imageRequired: false,
                imageRequiredMessage: 'Please upload LLPIN image.',
                size: '500kb',
                sizeMessage: 'Image size must not exceed 500KB.',
              },
            },
          },
        },
      ],
    },
    {
      id: 120,
      formType: 'RE_entityProfile',
      fieldName: 'gstin',
      fieldLabel: 'GSTIN',
      fieldFileName: 'gstinFile',
      fieldType: 'textfield_with_image',
      fieldPlaceholder: 'Enter GSTIN',
      fieldOrder: 10,
      fieldOrderGroup: 0,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
      conditionalLogic: [
        {
          when: {
            field: 'regulator',
            operator: 'not_equals',
            value: 'IFSCA',
          },
          then: {
            validationRules: {
              required: true,
              requiredMessage: 'GSTIN is required when Regulator is IFSCA.',
              maxLength: '15',
              maxLengthMessage: 'GSTIN must be 15 characters long.',
              minLength: '15',
              minLengthMessage: 'GSTIN must be 15 characters long.',
              regx: '^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}[Z]{1}[0-9A-Z]{1}$',
              regxMessage: 'Please enter a valid 15-character GSTIN.',
              validationFile: {
                imageFormat: ['jpeg', 'pdf', 'jpg'],
                imageRequired: true,
                imageRequiredMessage: 'Please upload GSTIN image.',
                size: '500kb',
                sizeMessage: 'File size must not exceed 500KB.',
              },
            },
          },
          else: {
            validationRules: {
              required: false,
              requiredMessage: 'GSTIN is required when Regulator is IFSCA.',
              maxLength: '15',
              maxLengthMessage: 'GSTIN must be 15 characters long.',
              minLength: '15',
              minLengthMessage: 'GSTIN must be 15 characters long.',
              regx: '^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}[Z]{1}[0-9A-Z]{1}$',
              regxMessage: 'Please enter a valid 15-character GSTIN.',
              validationFile: {
                imageFormat: ['jpeg', 'pdf', 'jpg'],
                imageRequired: false,
                imageRequiredMessage: 'Please upload GSTIN image.',
                size: '500kb',
                sizeMessage: 'File size must not exceed 500KB.',
              },
            },
          },
        },
      ],
    },
    {
      id: 121,
      formType: 'RE_entityProfile',
      fieldName: 'reWebsite',
      fieldLabel: 'RE Website URL',
      fieldType: 'textfield',
      fieldPlaceholder: 'Enter RE Website URL',
      validationRules: {
        required: false,
        maxLength: '100',
        maxLengthMessage: 'Website URL cannot exceed 100 characters.',
        regx: '^(https?:\\/\\/)?(www\\.)?[a-zA-Z0-9-]+\\.(com|in|co|org|net|ac\\.in|gov\\.in|co\\.in)(\\/[^\\s]*)?$',
        regxMessage: 'Please enter a valid website URL (e.g., example.com or https://example.com).',
      },
      fieldOrder: 11,
      fieldOrderGroup: 0,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
    },
    {
      id: 23,
      formType: 'RE_entityProfile',
      fieldName: 'addressProof',
      fieldLabel: 'Address Proof',
      fieldType: 'file',
      fieldPlaceholder: 'Upload Address Proof',
      validationRules: {
        required: true,
        imageFormat: ['jpeg', 'jpg', 'pdf'],
        size: '500kb',
        sizeMessage: 'Image size must not exceed 500KB.',
        requiredMessage: 'Address proof is required.',
      },
      fieldOrder: 12,
      fieldOrderGroup: 0,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
    },
    {
      id: 24,
      formType: 'RE_entityProfile',
      fieldName: 'other',
      fieldLabel: 'Other Document',
      fieldType: 'file',
      fieldPlaceholder: 'Upload Other Document',
      validationRules: {
        required: false,
        imageFormat: ['jpeg', 'jpg', 'pdf'],
        size: '500kb',
        sizeMessage: 'Image size must not exceed 500KB.',
      },
      fieldOrder: 13,
      fieldOrderGroup: 0,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
    },
  ],
  groupedFields: {},
  configuration: {
    id: 3,
    formType: 'RE_entityProfile',
    formTitle: 'Registration',
    formSubtitle: 'Entity Profile',
    formDescription: 'Fill out this form',
    formSettings: {
      formGroup: false,
      showProgress: false,
      enablecaptcha: false,
      isMultiSteps: true,
      stepsData: {
        nextStep: 'RE_addressDetails',
        currentStep: 'RE_entityProfile',
      },
    },
    submissionSettings: {
      clearButton: true,
      clearButtonText: 'Clear',
      submitButton: true,
      submitButtonText: 'Save and Next',
      validateIsGroup: false,
      validateButton: false,
    },
    isActive: true,
    languageSlug: 'en',
    formLayout: 'single-column',
    formTheme: 'modern',
    allowMultipleSubmissions: true,
    requiresAuthentication: false,
    parentId: 1,
  },
};

