// Frontend Form Configuration for Head of Institution Step
// This replaces the API call to GET /api/forms/RE_hoi/fields?is_group=true

import { FrontendFormConfig } from '../types/configTypes';
import { API_URL_REINITILIZE } from '../../../../../Constant';

export const headOfInstitutionConfig: FrontendFormConfig = {
  formType: 'RE_hoi',
  fields: [
    {
      id: 45,
      formType: 'RE_hoi',
      fieldName: 'hoiCitizenship',
      fieldLabel: 'Citizenship',
      fieldType: 'dropdown',
      fieldPlaceholder: 'Select Citizenship',
      fieldMaster: 'citizenship', // Will be fetched from API
      validationRules: {
        required: true,
        requiredMessage: 'Please select citizenship',
      },
      fieldOrder: 1,
      fieldOrderGroup: 0,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
    },
    {
      id: 46,
      formType: 'RE_hoi',
      fieldName: 'hoiCkycNo',
      fieldLabel: 'CKYC Number',
      fieldType: 'textfield_with_verify',
      fieldPlaceholder: 'Enter CKYC number',
      fieldOrder: 2,
      fieldOrderGroup: 0,
      isActive: true,
      isUnique: true,
      fieldWidth: 'full',
      languageSlug: 'en',
      conditionalLogic: [
        {
          when: {
            field: 'hoiCitizenship',
            operator: 'equals',
            value: 'Indian',
          },
          then: {
            validationRules: {
              required: true,
              requiredMessage: 'Please enter the CKYC number as Citizenship is India.',
              maxLength: '14',
              maxLengthMessage: 'CKYC number must be exactly 14 characters long.',
              minLength: '14',
              minLengthMessage: 'CKYC number must be exactly 14 characters long.',
              regx: '^[0-9]{14}$',
              regxMessage: 'CKYC number must contain only 14 digits.',
            },
            fieldAttributes: {
              type: 'external_api',
              trigger: 'blur',
              url: `${API_URL_REINITILIZE}/api/v1/otp/ckyc-verify`,
              method: 'POST',
              urlData: 'ckyc_number',
              responseMapping: {
                label: 'name',
                value: 'name',
              },
              description: 'Hit API when click in Verify CKYC button and citizenship selected is India',
              autoPopulate: ['hoiTitle', 'hoiFirstName', 'hoiLastName', 'hoiMiddleName', 'hoiGender'],
            },
          },
        },
      ],
    },
    {
      id: 47,
      formType: 'RE_hoi',
      fieldName: 'hoiTitle',
      fieldLabel: 'Title',
      fieldType: 'dropdown',
      fieldPlaceholder: 'Select Title',
      fieldMaster: 'titles', // Will be fetched from API
      validationRules: {
        required: true,
        requiredMessage: 'Please select a title',
      },
      fieldOrder: 3,
      fieldOrderGroup: 0,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
    },
    {
      id: 48,
      formType: 'RE_hoi',
      fieldName: 'hoiFirstName',
      fieldLabel: 'First Name',
      fieldType: 'textfield',
      fieldPlaceholder: 'Enter your first name',
      validationRules: {
        required: true,
        requiredMessage: 'Please enter your first name.',
        regx: "^(?!.*'.*')[A-Za-z .']+$",
        regxMessage: 'First Name can contain only letters, spaces, a single apostrophe, and dots.',
        maxLength: '33',
        maxLengthMessage: 'First Name cannot exceed 33 characters.',
        minLength: '2',
        minLengthMessage: 'First Name must be at least 2 characters.',
      },
      fieldOrder: 4,
      fieldOrderGroup: 0,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
    },
    {
      id: 49,
      formType: 'RE_hoi',
      fieldName: 'hoiMiddleName',
      fieldLabel: 'Middle Name',
      fieldType: 'textfield',
      fieldPlaceholder: 'Enter your middle name',
      validationRules: {
        required: false,
        regx: "^(?!.*'.*')[A-Za-z .']+$",
        regxMessage: 'Middle Name can contain only letters, spaces, a single apostrophe, and dots.',
        maxLength: '33',
        maxLengthMessage: 'Middle Name cannot exceed 33 characters.',
      },
      fieldOrder: 5,
      fieldOrderGroup: 0,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
    },
    {
      id: 50,
      formType: 'RE_hoi',
      fieldName: 'hoiLastName',
      fieldLabel: 'Last Name',
      fieldType: 'textfield',
      fieldPlaceholder: 'Enter your last name',
      validationRules: {
        required: false,
        regx: "^(?!.*'.*')[A-Za-z.']+$",
        regxMessage: 'Last Name can contain only letters, a single apostrophe, and dots. Spaces are not allowed.',
        maxLength: '33',
        maxLengthMessage: 'Last Name cannot exceed 33 characters.',
        minLength: '2',
        minLengthMessage: 'Last Name must be at least 2 characters.',
      },
      fieldOrder: 6,
      fieldOrderGroup: 0,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
    },
    {
      id: 51,
      formType: 'RE_hoi',
      fieldName: 'hoiGender',
      fieldLabel: 'Gender',
      fieldType: 'dropdown',
      fieldPlaceholder: 'Select Gender',
      fieldMaster: 'gender', // Will be fetched from API
      validationRules: {
        required: true,
        requiredMessage: 'Please select your gender.',
      },
      fieldOrder: 7,
      fieldOrderGroup: 0,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
    },
    {
      id: 52,
      formType: 'RE_hoi',
      fieldName: 'hoiDesignation',
      fieldLabel: 'Designation',
      fieldType: 'textfield',
      fieldPlaceholder: 'Enter your designation',
      validationRules: {
        required: true,
        requiredMessage: 'Please enter your designation',
        maxLength: '100',
        maxLengthMessage: 'Designation cannot exceed 100 characters.',
        regx: '^(?!.*\\s.*\\s)[A-Za-z0-9`~@#$%^&*()_+\\-= ]+$',
        regxMessage: 'Designation can only contain alphanumeric characters and the symbols `~@#$%^&*()_+-= are allowed.',
      },
      fieldOrder: 8,
      fieldOrderGroup: 0,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
    },
    {
      id: 53,
      formType: 'RE_hoi',
      fieldName: 'hoiEmail',
      fieldLabel: 'Email',
      fieldType: 'textfield',
      fieldPlaceholder: 'Enter your email',
      validationRules: {
        required: true,
        requiredMessage: 'Please enter your email address.',
        maxLength: '255',
        maxLengthMessage: 'Email address cannot exceed 255 characters.',
        regx: '^[A-Za-z0-9`~#$%^&*.()_+\\-=]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$',
        regxMessage: 'Please enter a valid email address.',
      },
      fieldOrder: 9,
      fieldOrderGroup: 0,
      isActive: true,
      isUnique: true,
      fieldWidth: 'full',
      languageSlug: 'en',
    },
    {
      id: 54,
      formType: 'RE_hoi',
      fieldName: 'hoiCountryCode',
      fieldLabel: 'Country Code',
      fieldType: 'dropdown',
      fieldPlaceholder: 'Select country code',
      fieldMaster: 'countryCode', // Will be fetched from API
      validationRules: {
        required: true,
        requiredMessage: 'Please select a country code.',
        maxLength: '60',
        maxLengthMessage: 'Valid length for country code is 60',
      },
      fieldOrder: 10,
      fieldOrderGroup: 0,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
    },
    {
      id: 55,
      formType: 'RE_hoi',
      fieldName: 'hoiMobile',
      fieldLabel: 'Mobile Number',
      fieldType: 'textfield',
      fieldPlaceholder: 'Enter mobile number',
      fieldOrder: 11,
      fieldOrderGroup: 0,
      isActive: true,
      isUnique: true,
      fieldWidth: 'full',
      languageSlug: 'en',
      conditionalLogic: [
        {
          when: {
            field: 'hoiCountryCode',
            operator: 'in',
            value: ['+91'],
          },
          then: {
            validationRules: {
              required: true,
              requiredMessage: 'Mobile number is required for Indian citizens.',
              maxLength: '10',
              maxLengthMessage: 'Mobile number must be 10 digits for Indian citizens.',
              minLength: '10',
              minLengthMessage: 'Mobile number must be 10 digits for Indian citizens.',
              numberValudation: true,
              regx: '^[0-9]{10}$',
              regxMessage: 'Mobile number must be 10 digits only.',
            },
          },
          else: {
            validationRules: {
              required: true,
              requiredMessage: 'Mobile number is required.',
              maxLength: '15',
              maxLengthMessage: 'Mobile number cannot exceed 15 digits.',
              minLength: '8',
              minLengthMessage: 'Mobile number must be at least 8 digits.',
              numberValudation: true,
              regx: '^[0-9]+$',
              regxMessage: 'Mobile number must contain only digits.',
            },
          },
        },
      ],
    },
    {
      id: 56,
      formType: 'RE_hoi',
      fieldName: 'hoiLandline',
      fieldLabel: 'Landline Number',
      fieldType: 'textfield',
      fieldPlaceholder: 'Enter landline number',
      validationRules: {
        required: false,
        regx: '^[0-9+ -]+$',
        regxMessage: 'Landline number can contain digits, +, space, and hyphen only.',
        maxLength: '15',
        maxLengthMessage: 'Landline number cannot exceed 15 digits.',
      },
      fieldOrder: 12,
      fieldOrderGroup: 0,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
    },
  ],
  groupedFields: {},
  configuration: {
    id: 5,
    formType: 'RE_hoi',
    formTitle: 'Head of Institution Details',
    formSubtitle: 'Head of Institution Details',
    formDescription: 'Fill out this form',
    formSettings: {
      formGroup: false,
      showProgress: false,
      enablecaptcha: false,
      isMultiSteps: true,
      stepsData: {
        nextStep: 'RE_nodal',
        previousStep: 'RE_addressDetails',
        currentStep: 'RE_hoi',
      },
    },
    submissionSettings: {
      clearButton: false,
      clearButtonText: 'Clear',
      submitButton: true,
      submitButtonText: 'Save and Next',
      validateIsGroup: false,
      validateButton: true,
      validateButtonText: 'Validate',
    },
    isActive: true,
    languageSlug: 'en',
    formLayout: 'single-column',
    formTheme: 'modern',
    allowMultipleSubmissions: true,
    requiresAuthentication: false,
    parentId: 1,
  },
};

