// Frontend Form Configuration for Nodal Officer Step
// This replaces the API call to GET /api/forms/RE_nodal/fields?is_group=true

import { FrontendFormConfig } from '../types/configTypes';
import { API_URL_REINITILIZE } from '../../../../../Constant';
export const nodalOfficerConfig: FrontendFormConfig = {
  formType: 'RE_nodal',
  fields: [
    {
      id: 57,
      formType: 'RE_nodal',
      fieldName: 'noCitizenship',
      fieldLabel: 'Citizenship',
      fieldType: 'dropdown',
      fieldPlaceholder: 'Select Citizenship',
      fieldMaster: 'citizenship', // Will be fetched from API
      validationRules: {
        required: true,
        requiredMessage: 'Please select citizenship',
      },
      fieldOrder: 1,
      fieldOrderGroup: 1,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
    },
    {
      id: 58,
      formType: 'RE_nodal',
      fieldName: 'noCkycNumber',
      fieldLabel: 'CKYC Number',
      fieldType: 'textfield_with_verify',
      fieldPlaceholder: 'Enter your CKYC number',
      fieldOrder: 2,
      fieldOrderGroup: 1,
      isActive: true,
      isUnique: true,
      fieldWidth: 'full',
      languageSlug: 'en',
      conditionalLogic: [
        {
          when: {
            field: 'noCitizenship',
            operator: 'equals',
            value: 'Indian',
          },
          then: {
            validationRules: {
              required: true,
              requiredMessage: 'Please enter the CKYC number as Citizenship is India.',
              maxLength: '14',
              maxLengthMessage: 'CKYC number must be exactly 14 characters long.',
              minLength: '14',
              minLengthMessage: 'CKYC number must be exactly 14 characters long.',
              regx: '^[0-9]{14}$',
              regxMessage: 'CKYC number must contain only 14 digits.',
            },
            fieldAttributes: {
              type: 'external_api',
              trigger: 'blur',
              url: `${API_URL_REINITILIZE}/api/v1/otp/ckyc-verify`,
              method: 'POST',
              urlData: 'ckyc_number',
              responseMapping: {
                label: 'name',
                value: 'name',
              },
              description: 'Hit API when click in Verify CKYC button and citizenship selected is India',
              autoPopulate: ['noTitle', 'noFirstName', 'noLastName', 'noMiddleName', 'noGender'],
            },
          },
        },
      ],
    },
    {
      id: 59,
      formType: 'RE_nodal',
      fieldName: 'noTitle',
      fieldLabel: 'Title',
      fieldType: 'dropdown',
      fieldPlaceholder: 'Select Title',
      fieldMaster: 'titles', // Will be fetched from API
      validationRules: {
        required: true,
        requiredMessage: 'Please select a title (Mr./Mrs./Ms.).',
      },
      fieldOrder: 3,
      fieldOrderGroup: 1,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
    },
    {
      id: 60,
      formType: 'RE_nodal',
      fieldName: 'noFirstName',
      fieldLabel: 'First Name',
      fieldType: 'textfield',
      fieldPlaceholder: 'Enter your first name',
      validationRules: {
        required: true,
        requiredMessage: 'Enter your first name.',
        regx: "^(?!.*'.*')[A-Za-z .']+$",
        regxMessage: 'First Name can only contain letters, spaces, single apostrophes, dots.',
        maxLength: '33',
        maxLengthMessage: 'First Name cannot exceed 33 characters.',
        minLength: '2',
        minLengthMessage: 'First Name must be at least 2 characters.',
      },
      fieldOrder: 4,
      fieldOrderGroup: 1,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
    },
    {
      id: 61,
      formType: 'RE_nodal',
      fieldName: 'noMiddleName',
      fieldLabel: 'Middle Name',
      fieldType: 'textfield',
      fieldPlaceholder: 'Enter your middle name',
      validationRules: {
        required: false,
        regx: "^(?!.*'.*')[A-Za-z .']+$",
        regxMessage: 'Middle Name can only contain letters, spaces, single apostrophes, dots.',
        maxLength: '33',
        maxLengthMessage: 'Middle Name cannot exceed 33 characters.',
        minLength: '2',
        minLengthMessage: 'Middle Name must be at least 2 characters if entered.',
      },
      fieldOrder: 5,
      fieldOrderGroup: 1,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
    },
    {
      id: 62,
      formType: 'RE_nodal',
      fieldName: 'noLastName',
      fieldLabel: 'Last Name',
      fieldType: 'textfield',
      fieldPlaceholder: 'Enter your last name',
      validationRules: {
        required: false,
        regx: "^(?!.*'.*')[A-Za-z.']+$",
        regxMessage: 'Last Name can only contain letters, single apostrophes, and dots. Spaces are not allowed.',
        maxLength: '33',
        maxLengthMessage: 'Last Name cannot exceed 33 characters.',
        minLength: '2',
        minLengthMessage: 'Last Name must be at least 2 characters.',
      },
      fieldOrder: 6,
      fieldOrderGroup: 1,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
    },
    {
      id: 63,
      formType: 'RE_nodal',
      fieldName: 'noGender',
      fieldLabel: 'Gender',
      fieldType: 'dropdown',
      fieldPlaceholder: 'Select gender',
      fieldMaster: 'gender', // Will be fetched from API
      validationRules: {
        required: true,
        requiredMessage: 'Please select your gender.',
      },
      fieldOrder: 7,
      fieldOrderGroup: 1,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
    },
    {
      id: 64,
      formType: 'RE_nodal',
      fieldName: 'noDob',
      fieldLabel: 'Date of Birth',
      fieldType: 'date',
      fieldPlaceholder: 'Enter your DOB',
      validationRules: {
        required: true,
        requiredMessage: 'Please select your DOB.',
        isAdultAge: '18',
        maxDate: 'true',
      },
      fieldOrder: 8,
      fieldOrderGroup: 1,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
    },
    {
      id: 65,
      formType: 'RE_nodal',
      fieldName: 'noDesignation',
      fieldLabel: 'Designation',
      fieldType: 'textfield',
      fieldPlaceholder: 'Enter your designation',
      validationRules: {
        required: true,
        requiredMessage: 'Please enter your designation',
        maxLength: '100',
        maxLengthMessage: 'Designation cannot exceed 100 characters.',
        regx: '^(?!.*\\s.*\\s)[A-Za-z0-9`~@#$%^&*()_+\\-= ]+$',
        regxMessage: 'Designation can only contain alphanumeric characters and the symbols `~@#$%^&*()_+-= are allowed.',
      },
      fieldOrder: 9,
      fieldOrderGroup: 1,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
    },
    {
      id: 66,
      formType: 'RE_nodal',
      fieldName: 'noEmployCode',
      fieldLabel: 'Employee Code',
      fieldFileName: 'noEmployCodeFile',
      fieldType: 'textfield_with_image',
      fieldPlaceholder: 'Enter employee code',
      validationRules: {
        required: true,
        requiredMessage: 'Employee Code is required',
        regx: '^[A-Za-z0-9+]{0,50}$',
        regxMessage: 'Employee code must be alphanumeric',
        maxLength: '50',
        maxLengthMessage: 'Enter value not mroe then 50',
        validationFile: {
          imageFormat: ['jpeg', 'jpg', 'pdf'],
          imageRequired: true,
          imageRequiredMessage: 'Please upload image',
          size: '500kb',
          sizeMessage: 'Image not more then 500 KB',
        },
      },
      fieldOrder: 10,
      fieldOrderGroup: 1,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
    },
    {
      id: 67,
      formType: 'RE_nodal',
      fieldName: 'noEmail',
      fieldLabel: 'Email',
      fieldType: 'textfield',
      fieldPlaceholder: 'Enter your email id',
      validationRules: {
        required: true,
        requiredMessage: 'Please enter your email address.',
        maxLength: '254',
        maxLengthMessage: 'Email address cannot exceed 254 characters.',
        regx: '^(?=.*@)[A-Za-z0-9`~@#$%^&*.()_+\\-=]+$',
        regxMessage: 'Please enter a valid email address format.',
      },
      fieldOrder: 11,
      fieldOrderGroup: 1,
      isActive: true,
      isUnique: true,
      fieldWidth: 'full',
      languageSlug: 'en',
    },
    {
      id: 68,
      formType: 'RE_nodal',
      fieldName: 'noCountryCode',
      fieldLabel: 'Country Code',
      fieldType: 'dropdown',
      fieldPlaceholder: 'Select country code',
      fieldMaster: 'countryCode', // Will be fetched from API
      validationRules: {
        required: true,
        requiredMessage: 'Please select a country code.',
        maxLength: '60',
        maxLengthMessage: 'Valid length for country code is 60 characer',
      },
      fieldOrder: 12,
      fieldOrderGroup: 1,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
    },
    {
      id: 69,
      formType: 'RE_nodal',
      fieldName: 'noMobileNumber',
      fieldLabel: 'Mobile Number',
      fieldType: 'textfield',
      fieldPlaceholder: 'Enter your mobile number',
      fieldOrder: 13,
      fieldOrderGroup: 1,
      isActive: true,
      isUnique: true,
      fieldWidth: 'full',
      languageSlug: 'en',
      conditionalLogic: [
        {
          when: {
            field: 'noCountryCode',
            operator: 'in',
            value: ['+91'],
          },
          then: {
            validationRules: {
              required: true,
              requiredMessage: 'Mobile number is required for Indian citizens.',
              maxLength: '10',
              maxLengthMessage: 'Mobile number must be 10 digits for Indian citizens.',
              minLength: '10',
              minLengthMessage: 'Mobile number must be 10 digits for Indian citizens.',
              numberValudation: true,
              regx: '^[0-9]{10}$',
              regxMessage: 'Mobile number must be 10 digits only.',
            },
          },
          else: {
            validationRules: {
              required: true,
              requiredMessage: 'Mobile number is required.',
              maxLength: '15',
              maxLengthMessage: 'Mobile number cannot exceed 15 digits.',
              minLength: '8',
              minLengthMessage: 'Mobile number must be at least 8 digits.',
              numberValudation: true,
              regx: '^[0-9]+$',
              regxMessage: 'Mobile number must contain only digits.',
            },
          },
        },
      ],
    },
    {
      id: 70,
      formType: 'RE_nodal',
      fieldName: 'noLandline',
      fieldLabel: 'Landline Number',
      fieldType: 'textfield',
      fieldPlaceholder: 'Enter landline number',
      validationRules: {
        required: false,
        regx: '^[A-Za-z0-9+]{0,15}$',
        regxMessage: 'Landline number must contain only digits.',
        maxLength: '15',
        maxLengthMessage: 'Landline number cannot exceed 15 digits.',
      },
      fieldOrder: 14,
      fieldOrderGroup: 1,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
    },
    // Office Address dropdown (id: 71)
    {
      id: 71,
      formType: 'RE_nodal',
      fieldName: 'noOfficeAddress',
      fieldLabel: 'Office Address',
      fieldType: 'dropdown',
      fieldPlaceholder: 'Select office address',
      fieldOptions: [
        {
          code: 'Same as registered address',
          name: 'Same as registered address',
        },
        {
          code: 'Same as correspondence address',
          name: 'Same as correspondence address',
        },
      ],
      validationRules: {
        required: true,
        requiredMessage: 'Please select office address',
      },
      fieldOrder: 15,
      fieldOrderGroup: 1,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
    },
    // Address fields (IDs 510-519)
    {
      id: 510,
      formType: 'RE_nodal',
      fieldName: 'noAddressLine1',
      fieldLabel: 'Address Line 1',
      fieldType: 'textfield',
      fieldPlaceholder: 'Enter office address line 1',
      validationRules: {
        required: true,
        requiredMessage: 'Please enter address line 1',
        maxLength: '60',
        maxLengthMessage: 'Max length for address is 60',
        regx: '^[A-Za-z0-9 `~@#$%^&*()_+\\-=,.]+$',
        regxMessage: 'Only alphanumeric, spaces, and `~@#$%^&*()_+-=,. are allowed.',
      },
      fieldOrder: 16,
      fieldOrderGroup: 1,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
    },
    {
      id: 511,
      formType: 'RE_nodal',
      fieldName: 'noAddressLine2',
      fieldLabel: 'Address Line 2',
      fieldType: 'textfield',
      fieldPlaceholder: 'Enter office address line 2',
      validationRules: {
        required: false,
        maxLength: '60',
        maxLengthMessage: 'Max length for address is 60',
        regx: '^[A-Za-z0-9 `~@#$%^&*()_+\\-=,.]+$',
        regxMessage: 'Only alphanumeric, spaces, and `~@#$%^&*()_+-=,. are allowed.',
      },
      fieldOrder: 17,
      fieldOrderGroup: 1,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
    },
    {
      id: 512,
      formType: 'RE_nodal',
      fieldName: 'noAddressLine3',
      fieldLabel: 'Address Line 3',
      fieldType: 'textfield',
      fieldPlaceholder: 'Enter office address line 3',
      validationRules: {
        required: false,
        maxLength: '60',
        maxLengthMessage: 'Max length for address is 60',
        regx: '^[A-Za-z0-9 `~@#$%^&*()_+\\-=,.]+$',
        regxMessage: 'Only alphanumeric, spaces, and `~@#$%^&*()_+-=,. are allowed.',
      },
      fieldOrder: 18,
      fieldOrderGroup: 1,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
    },
    {
      id: 513,
      formType: 'RE_nodal',
      fieldName: 'noRegisterCountry',
      fieldLabel: 'Country',
      fieldType: 'dropdown',
      fieldPlaceholder: 'Select country',
      fieldMaster: 'countryCode',
      validationRules: {
        required: true,
        requiredMessage: 'Please select country',
        maxLength: '60',
        maxLengthMessage: 'Max length for country is 60',
      },
      fieldOrder: 19,
      fieldOrderGroup: 1,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
    },
    {
      id: 514,
      formType: 'RE_nodal',
      fieldName: 'noRegisterState',
      fieldLabel: 'State / UT',
      fieldType: 'textfield',
      fieldPlaceholder: 'Select state',
      fieldOrder: 20,
      fieldOrderGroup: 1,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
      conditionalLogic: [
        {
          when: {
            field: 'noRegisterCountry',
            operator: 'equals',
            value: 'India',
          },
          then: {
            validationRules: {
              required: true,
              requiredMessage: 'Please select state',
              maxLength: '60',
              maxLengthMessage: 'Max length for state is 60',
            },
          },
          else: {
            validationRules: {
              required: false,
              maxLength: '60',
              maxLengthMessage: 'Max length for state is 60',
            },
          },
        },
      ],
      fieldAttributes: {
        type: 'external_api',
        trigger: 'blur',
        url: '/api/masters/state/{noRegisterCountry}/formatted',
        method: 'GET',
        urlData: 'noRegisterCountry',
        responseMapping: {
          label: 'name',
          value: 'code',
        },
      },
    },
    {
      id: 515,
      formType: 'RE_nodal',
      fieldName: 'noRegisterDistrict',
      fieldLabel: 'District',
      fieldType: 'textfield',
      fieldPlaceholder: 'District',
      fieldOrder: 21,
      fieldOrderGroup: 1,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
      conditionalLogic: [
        {
          when: {
            field: 'noRegisterCountry',
            operator: 'equals',
            value: 'India',
          },
          then: {
            validationRules: {
              required: true,
              requiredMessage: 'Please select district',
              maxLength: '40',
              maxLengthMessage: 'Max length for district is 40',
            },
          },
          else: {
            validationRules: {
              required: false,
              maxLength: '40',
              maxLengthMessage: 'Max length for district is 40',
            },
          },
        },
      ],
      fieldAttributes: {
        type: 'external_api',
        trigger: 'blur',
        url: '/api/masters/district/{noRegisterState}/formatted',
        method: 'GET',
        urlData: 'noRegisterState',
        responseMapping: {
          label: 'name',
          value: 'code',
        },
      },
    },
    {
      id: 516,
      formType: 'RE_nodal',
      fieldName: 'noRegisterCity',
      fieldLabel: 'City / Town',
      fieldType: 'textfield',
      fieldPlaceholder: 'Enter your city',
      fieldOrder: 22,
      fieldOrderGroup: 1,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
      conditionalLogic: [
        {
          when: {
            field: 'noRegisterCountry',
            operator: 'equals',
            value: 'India',
          },
          then: {
            validationRules: {
              required: true,
              requiredMessage: 'Please enter city',
              maxLength: '60',
              maxLengthMessage: 'Max length for city is 60',
            },
          },
          else: {
            validationRules: {
              required: false,
              maxLength: '60',
              maxLengthMessage: 'Max length for city is 60',
            },
          },
        },
      ],
    },
    {
      id: 517,
      formType: 'RE_nodal',
      fieldName: 'noRegisterPincode',
      fieldLabel: 'Pin Code',
      fieldType: 'textfield',
      fieldPlaceholder: 'Select pin code',
      fieldOrder: 23,
      fieldOrderGroup: 1,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
      conditionalLogic: [
        {
          when: {
            field: 'noRegisterCountry',
            operator: 'equals',
            value: 'India',
          },
          then: {
            validationRules: {
              required: true,
              requiredMessage: 'Please select PIN CODE',
              maxLength: '6',
              maxLengthMessage: 'Max length for pin code is 6',
            },
          },
          else: {
            validationRules: {
              required: false,
              numberValudation: true,
              maxLength: '6',
              maxLengthMessage: 'Max length for pin code is 6',
            },
          },
        },
      ],
      fieldAttributes: {
        type: 'external_api',
        trigger: 'blur',
        url: '/api/masters/pincode/{noRegisterDistrict}/formatted',
        method: 'GET',
        urlData: 'noRegisterDistrict',
        responseMapping: {
          label: 'name',
          value: 'code',
        },
      },
    },
    {
      id: 518,
      formType: 'RE_nodal',
      fieldName: 'noRegisterPincodeOther',
      fieldLabel: 'Pin Code (in case of others)',
      fieldType: 'textfield',
      fieldPlaceholder: 'Enter your other pin code',
      fieldOrder: 24,
      fieldOrderGroup: 1,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
      conditionalLogic: [
        {
          when: {
            field: 'noRegisterPincode',
            operator: 'equals',
            value: 'other',
          },
          then: {
            validationRules: {
              required: true,
              requiredMessage: 'Enter Pin code other',
              numberValudation: true,
              regx: '^[0-9]{6}$',
              regxMessage: 'Pin code only accepts 6 digits',
              maxLength: '6',
              maxLengthMessage: 'Max length for pin code is 6',
            },
          },
          else: {
            validationRules: {
              required: false,
              numberValudation: true,
              maxLength: '50',
              maxLengthMessage: 'Max length for pin code is 50',
            },
          },
        },
      ],
    },
    {
      id: 519,
      formType: 'RE_nodal',
      fieldName: 'noRegisterDigipin',
      fieldLabel: 'Digipin',
      fieldType: 'textfield',
      fieldPlaceholder: 'Enter your digipin',
      validationRules: {
        required: false,
        maxLength: '12',
        maxLengthMessage: 'Max length for digipin is 12',
        regx: '^[2-9CFJKLMPT]{3}-[2-9CFJKLMPT]{3}-[2-9CFJKLMPT]{4}$',
        regxMessage: 'Please enter a valid Digipin (eg: 29C-45F-7JMT). Only digits 2-9 and letters C,F,J,K,L,M,P,T are allowed.',
      },
      fieldOrder: 25,
      fieldOrderGroup: 1,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
    },
    // Proof of Identity (id: 72)
    {
      id: 72,
      formType: 'RE_nodal',
      fieldName: 'noProofOfIdentity',
      fieldLabel: 'Proof of Identity',
      fieldType: 'dropdown',
      fieldPlaceholder: 'Select proof of identity',
      fieldMaster: 'proofOfIdentities',
      validationRules: {
        required: true,
        requiredMessage: 'Please select proof of identity',
      },
      fieldOrder: 26,
      fieldOrderGroup: 1,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
    },
    // Proof of Identity Number (id: 73)
    {
      id: 73,
      formType: 'RE_nodal',
      fieldName: 'noProofOfIdentityNumber',
      fieldLabel: 'Proof of Identity Number',
      fieldFileName: 'noProofOfIdentityNumberFile',
      fieldType: 'textfield_with_image',
      fieldPlaceholder: 'Enter number',
      validationRules: {
        required: true,
        requiredMessage: 'Enter proof of identity number and file',
        validationFile: {
          imageFormat: ['jpeg', 'pdf', 'jpg'],
          imageRequired: true,
          imageRequiredMessage: 'Please upload image',
          size: '500kb',
          sizeMessage: 'Image not more than 500 KB',
        },
      },
      fieldOrder: 27,
      fieldOrderGroup: 1,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
    },
    // Date of Board Resolution for Appointment (id: 74)
    {
      id: 74,
      formType: 'RE_nodal',
      fieldName: 'noBoardResoluationDate',
      fieldLabel: 'Date of Board Resolution for Appointment',
      fieldType: 'date',
      fieldPlaceholder: 'Select date',
      validationRules: {
        required: true,
        requiredMessage: 'Please select the date.',
        maxDate: 'true',
      },
      fieldOrder: 28,
      fieldOrderGroup: 1,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
    },
    // Board Resolution (id: 520)
    {
      id: 520,
      formType: 'RE_nodal',
      fieldName: 'noBoardResoluation',
      fieldLabel: 'Board Resolution',
      fieldType: 'file',
      fieldPlaceholder: 'Upload board resolution',
      validationRules: {
        required: true,
        requiredMessage: 'Board Resolution is required',
        validationFile: {
          imageFormat: ['jpeg', 'jpg', 'pdf'],
          size: '500kb',
          sizeMessage: 'Document not more than 500 KB',
        },
      },
      fieldOrder: 29,
      fieldOrderGroup: 1,
      isActive: true,
      isUnique: false,
      fieldWidth: 'full',
      languageSlug: 'en',
    },
  ],
  groupedFields: {},
  configuration: {
    id: 6,
    formType: 'RE_nodal',
    formTitle: 'Nodal Officer Details',
    formSubtitle: 'Nodal Officer Details',
    formDescription: 'Fill out this form',
    formSettings: {
      formGroup: false,
      showProgress: false,
      enablecaptcha: false,
      isMultiSteps: true,
      stepsData: {
        nextStep: 'RE_iau',
        previousStep: 'RE_hoi',
        currentStep: 'RE_nodal',
      },
    },
    submissionSettings: {
      clearButton: false,
      clearButtonText: 'Clear',
      submitButton: true,
      submitButtonText: 'Save and Next',
      validateIsGroup: false,
      validateButton: true,
      validateButtonText: 'Validate',
    },
    isActive: true,
    languageSlug: 'en',
    formLayout: 'single-column',
    formTheme: 'modern',
    allowMultipleSubmissions: true,
    requiresAuthentication: false,
    parentId: 1,
  },
};

