FROM node:20 AS builder
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
ARG REACT_APP_API_BASE_URL
ARG REACT_APP_API_BASE_URL_ADMIN
ARG REACT_APP_API_BASE_DROPDOWN_URL
ARG REACT_APP_BACKEND_ENV
ARG REACT_APP_CMS_URL
ARG NODE_PATH
ENV REACT_APP_API_BASE_URL=$REACT_APP_API_BASE_URL
ENV REACT_APP_API_BASE_URL_ADMIN=$REACT_APP_API_BASE_URL_ADMIN
ENV REACT_APP_API_BASE_DROPDOWN_URL=$REACT_APP_API_BASE_DROPDOWN_URL
ENV REACT_APP_BACKEND_ENV=$REACT_APP_BACKEND_ENV
ENV REACT_APP_CMS_URL=$REACT_APP_CMS_URL
ENV NODE_PATH=$NODE_PATH
ENV PUBLIC_URL=/ckyc
RUN npm run build

FROM nginx:alpine
# Add this line - copy custom nginx config
COPY nginx.conf /etc/nginx/conf.d/default.conf
WORKDIR /usr/share/nginx/html
RUN rm -rf ./*
COPY --from=builder /app/build .
EXPOSE 7050
CMD ["nginx", "-g", "daemon off;"]
