// src/mock/mockWorkflowData.ts

export const mockWorkflowData = {
  success: true,
  data: {
    workflowId: 'c7fa023f-70ba-4909-b711-c0ba1886538b',
    workflowType: 'RE_REGISTRATION',
    status: 'SUBMITTED',
    payload: {
      hoi: {
        hoiEmail: 'alice.johnson@example.com',
        hoiTitle: 'Mr.',
        hoiGender: 'Female',
        hoiLastName: 'LN',
        hoiFirstName: 'MN',
        hoiCkycNumber: '11111111111134',
        hoiMiddleName: 'Nagraj',
        hoiCitizenship: 'Indian',
        hoiCountryCode: '+91',
        hoiDesignation: 'Principal',
        hoiMobileNumbmer: '9879846710',
        hoiLandlineNumber: '08012345678',
      },
      addresses: {
        addressLine1: '123 Registered St',
        addressLine2: 'Near Park',
        addressLine3: 'Block A',
        registerCity: 'Bangalore',
        registerState: 'Karnataka',
        registerCountry: 'IN',
        registerDigipin: '435H',
        registerPincode: '560001',
        registerDistrict: 'Bangalore Urban',
        correspondenceCity: 'Bangalore',
        correspondenceState: 'Karnataka',
        registerPincodeOther: '560002',
        correspondenceCountry: 'IN',
        correspondenceDigipin: '234TF',
        correspondencePincode: '560003',
        correspondenceDistrict: 'Bangalore Urban',
        correspondenceAddressLine1: '456 Corr St',
        correspondenceAddressLine2: '2nd Floor',
        correspondenceAddressLine3: 'Sector 5',
        correspondencePincodeOther: '560004',
        sameAsCorrespondenceAddress: false,
      },
      submission: {
        submittedAt: '2025-10-23T09:03:41.843733Z',
        submittedBy: 'NO_8561',
      },
      nodalOfficer: {
        noDob: '1990-01-01',
        noEmail: 'vnnchetana@gmail.com',
        noTitle: 'Ms',
        noGender: 'Male',
        noLastName: 'KL',
        noFirstName: 'JKLH',
        mobileNumber: '8888665421',
        noCkycNumber: '11223344551122',
        noEmployCode: 'E002',
        noMiddleName: 'VN',
        noCitizenship: 'Indian',
        noCountryCode: '+91',
        noDesignation: 'Nodal_Officer',
        noNobileNumber: '11111111111121',
        noOfficeAddress: false,
        noLandlineNumber: '08087654321',
        noProofOfIdentity: 'AADHAAR',
        noBoardResoluationDate: '2023-06-01',
        noProofOfIdentityNumber: '123412341234',
      },
      entityDetails: {
        cinNo: 'C12345DL2012PLC098765',
        panNo: 'CACBT5677H',
        gstinNo: '29ABCDE1234F2Z5',
        llpinNo: 'LLPIN98',
        reWebsite: 'www.LatestAdmin.com',
        regulator: 'RBI',
        constitution: 'B',
        proprietorName: 'John Doe',
        registrationNo: 'REG123458',
        institutionType: 'Foreign Exchange Business',
        nameOfInstitution: 'ABC Institution',
      },
      institutionalAdminUser: {
        iauDob1: '1985-05-15',
        iauDob2: '1988-09-21',
        iauEmail1: 'charlie.brown@example.com',
        iauEmail2: 'diana.prince@example.com',
        iauTitle1: 'Mrs.',
        iauTitle2: 'Mrs.',
        iauGender1: 'Male',
        iauGender2: 'Female',
        iauLastName1: 'Johnson',
        iauLastName2: 'Johnson',
        iauFirstName1: 'Alice',
        iauFirstName2: 'Alice',
        iauCkycNumber1: '11111111111137',
        iauCkycNumber2: '11111111111139',
        iauEmployCode1: 'EMP1234',
        iauEmployCode2: 'EMP5678',
        iauMiddleName1: 'Harry',
        iauMiddleName2: 'Harry',
        iauCitizenship1: 'Indian',
        iauCitizenship2: 'Indian',
        iauCountryCode1: '+91',
        iauCountryCode2: '+91',
        iauDesignation1: 'Admin',
        iauDesignation2: 'Admin',
        iauMobileNumbmer1: '9127456780',
        iauMobileNumbmer2: '9981998899',
        iauOfficeAddress1: true,
        iauOfficeAddress2: false,
        iauLandLineNumber1: '08099887766',
        iauLandLineNumber2: '08066778899',
        iauProofOfIdentity1: 'PASSPORT',
        iauProofOfIdentity2: 'VOTER_ID',
        iauAuthorizationLetter1: 'Authorized+by+Board',
        iauAuthorizationLetter2: 'Signed+Authorizaty',
        iauDateOfAuthorization1: '2024-12-01',
        iauDateOfAuthorization2: '2025-01-15',
        iauProofOfIdentityNumber1: 'M1234567',
        iauProofOfIdentityNumber2: 'KA123456789',
      },
    },
    currentStep: 'submission',
    executedSteps: [
      'STARTED',
      'entityDetails',
      'addresses',
      'nodalOfficer',
      'institutionalAdminUser',
      'submission',
    ],
    documents: [
      {
        fieldKey: 'RE_REGISTRATION',
        type: 'cinFile',
        id: 'a3d951ea-1d8d-4521-bef4-f48f6523fdca',
      },
      {
        fieldKey: 'RE_REGISTRATION',
        type: 'panFile',
        id: 'd8e518a4-0a98-415a-ac44-d0736eeb9b1b',
      },
      {
        fieldKey: 'RE_REGISTRATION',
        type: 'registration_application_pdf',
        id: 'f975b4ba-0abe-4da1-ac37-9ea50f180779',
      },
      {
        fieldKey: 'RE_REGISTRATION',
        type: 'registration_signed_application_pdf',
        id: 'af43c340-c60a-4d7f-bcca-62bc06921b45',
      },
    ],
  },
  message: 'Workflow retrieved successfully',
};
