// src/enums/userRoles.enum.ts
export enum REUserRoles {
  INSTITUTIONAL_USER = 'INSTITUTIONAL_USER',
  INSTITUTIONAL_REGIONAL_USER = 'INSTITUTIONAL_REGIONAL_USER',
  INSTITUTIONAL_BRANCH_USER = 'INSTITUTIONAL_BRANCH_USER',
  INSTITUTIONAL_REGIONAL_ADMIN = 'INSTITUTIONAL_REGIONAL_ADMIN',
  INSTITUTIONAL_ADMIN_USER = 'INSTITUTIONAL_ADMIN_USER',
  INDIVIDUAL_USER = 'INDIVIDUAL_USER',
}

export const allowedGroupsCersai = [
  'Super_Admin_User',
  'Admin_User',
  'Operational_User',
];

export enum CERSAIUserRoles {
  SUPER_ADMIN_USER = 'SUPER_ADMIN_USER',
  ADMIN_USER = 'ADMIN_USER',
  OPERATIONAL_USER = 'OPERATIONAL_USER',
}
