import { ICreateKyc } from './interfaceCreateKyc';

export const data: ICreateKyc = {
  DemographicDetailForm: {
    dob: undefined,
    minor: 'No',
    nameMatch: 'Yes',
    dobMatch: 'Yes',
    photoMatch: 'Yes',
    gender: 'Male',
    genderMatch: 'Yes',
    panCard: '',
    form60: null,
    form61: null,
    panVerified: 'Yes',
    residentialStatus: '',
    residentialStatusDoc: 'Yes',
    education: '',
    educationDoc: 'Yes',
    nationality: 'india',
    nationalityDoc: 'Yes',
    occupation: 'Employed',
    occupationSupportDoc: 'Yes',
    disability: 'No',
    DisabilitySupportDoc: 'No',
    UDIDNumber: 'hehehheheh',
    imageFile: null,
    residentalStatusFile: null,
    EQFile: null,
    occupationFile: null,
    DisabilityStatusFile: null,
    nameDetail: {
      firstName: 'rohit ',
      middleName: '',
      lastName: 'sharma',
    },
    maidenName: {
      firstName: '',
      middleName: '',
      lastName: '',
    },
    motherName: {
      firstName: 'rohit ',
      middleName: '',
      lastName: 'sharma',
    },
    fatherName: {
      firstName: 'rohit',
      middleName: '',
      lastName: 'sharma',
    },
    spouseName: {
      firstName: 'rohit',
      middleName: '',
      lastName: 'sharma',
    },
  },
  ProofOfIdentityForm: {
    ovdType: 'passport',
    passportExpiryDate: undefined,
    drivingLicenseExpiryDate: undefined,
    idNumber: 'sssss',
    ovdCertifiedWithOriginal: 'Yes',
    certifiedCopyVerified: 'Yes',
    equivalentEDoc: 'Yes',
    documentVerifiedFromDigilocker: 'Yes',
    presenceOfPassportInMEA: 'Yes',
    presenceOfVoterIdInECI: 'Yes',
    presenceOfDrivingLicenseInRTO: 'Yes',
    presenceOfNREGA: 'Yes',
    presenceOfNPR: 'Yes',
    offlineVerificationOfAadhaar: 'Yes',
    dataReceivedFromOfflineVerification: '',
    ekycAuthentication: '',
    ekycDataReceivedFromUIDAI: '',
    ekycAuthenticationBiometric: '',
    ekycOtpAuthentication: '',
    copyOfOvdPoi: null,
  },
  AddressDetailForm: {
    permanentHouseNo: '302',
    permanentApartmentName: '195',
    permanentStreet: 'green park',
    permanentVillage: 'new delhi',
    permanentState: 'delhi',
    permanentCity: 'new delhi',
    permanentPinCode: '303030303030',
    permanentCountryCode: '19',
    permanentAddressSupported: 'Yes',
    permanentExactlyMatchWithOvd: 'Yes',
    permanentPartialMatchWithOvd: 'No',
    sameAsPermanent: 'Yes',
    currentHouseNo: '',
    currentApartmentName: '',
    currentStreet: '',
    currentVillage: '',
    currentState: '',
    currentCity: '',
    currentPinCode: '',
    currentCountryCode: '',
    deemedProofOfAddress: '',
    deemedPoAVerified: '',
    declaredAddress: '',
    geoTagged: '',
    currentAddressExactlyMatchWithOvd: '',
    currentPositiveVerification: '',
    currentPhysicalVerificationByThirdParty: '',
    currentPhysicalVerificationByReOfficial: '',
    otherDocument: null,
  },
  ContactDetailsForm: {
    email: '',
    countryCode: '',
    mobileNumber: '',
    mobileVerifiedOtp: '',
    emailVerifiedOtp: '',
    mobileVerifiedThirdParty: '',
  },
  NodalOfficerDetailForm: {
    relation: 'Authorized representative',
    ckycNumber: 'hehehehhehe',
  },
  AttestationDetailForm: {
    remarks: '',
    videoKycWithoutOfficial: '',
    digitalKycProcess: '',
    faceToFaceWithOfficial: '',
    nonFaceToFaceOnboarding: '',
    faceToFaceOnboarding: '',
    date: null,
    empName: '',
    empCode: '',
    empDesignation: '',
    empBranch: '',
    empCkycId: '',
    institutionName: '',
    institutionCode: '',
  },
};
