import { styled } from '@mui/material/styles';
import { Accordion, AccordionSummary } from '@mui/material';

export const StyledAccordion = styled(Accordion)(({ theme }) => ({
  marginBottom: theme.spacing(3),
  boxShadow: 'none',
  border: '1px solid #E6EBFF',
  borderRadius: '8px',
  '&:before': {
    display: 'none',
  },
  '&.Mui-expanded': {
    margin: 0,
    marginBottom: theme.spacing(3),
  },
}));

export const StyledAccordionSummary = styled(AccordionSummary)({
  padding: '0 16px',
  minHeight: '48px !important',
  backgroundColor: '#E6EBFF',
  borderRadius: '8px 8px 0 0',
  '& .MuiAccordionSummary-content': {
    margin: '12px 0 !important',
    fontWeight: 600,
  },
});

export const styles = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
    p: 2,
    backgroundColor: '#FFFFFF',
    minHeight: '100vh',
  },
  backButtonContainer: {
    display: 'flex',
    justifyContent: 'flex-end',
    width: '100%',
  },
  backButton: {
    color: 'black',
    textTransform: 'none',
    fontSize: '14px',
    fontFamily: 'Gilroy',
  },
  signedDocBanner: {
    width: '100%',
    height: '50px',
    backgroundColor: '#F8F9FD',
    border: '1px solid #E6EBFF',
    borderRadius: '4px',
    marginBottom: '16px',
    display: 'flex',
    alignItems: 'center',
    padding: '0 16px',
  },
  viewSignedDocLink: {
    color: '#002CBA',
    cursor: 'pointer',
    textDecoration: 'underline',
    textUnderlineOffset: '3px',
    fontWeight: 600,
    fontSize: '14px',
    fontFamily: 'Gilroy',
  },
  sectionTitle: {
    fontFamily: 'Gilroy',
    fontWeight: 700,
    fontSize: '18px',
    color: '#1A1A1A',
    mb: 2,
    mt: -2,
  },
  fieldLabel: {
    fontFamily: 'Gilroy',
    fontWeight: 600,
    fontSize: '14px',
    color: '#1A1A1A',
    mb: 0.5,
  },
  fieldInput: {
    '& .MuiOutlinedInput-root': {
      backgroundColor: '#F8F9FA',
      borderRadius: '4px',
      '& fieldset': {
        borderColor: '#DCE3FF',
      },
      '&:hover fieldset': {
        borderColor: '#002CBA',
      },
      '&.Mui-focused fieldset': {
        borderColor: '#002CBA',
      },
      '&.Mui-disabled': {
        backgroundColor: '#F8F9FA',
        '& fieldset': {
          borderColor: '#DCE3FF',
        },
      },
    },
    '& .MuiInputBase-input': {
      fontSize: '14px',
      fontFamily: 'Gilroy',
      color: '#1A1A1A',
      padding: '10px 12px',
      '&.Mui-disabled': {
        WebkitTextFillColor: '#1A1A1A',
        opacity: 1,
      },
    },
  },
  docFieldLabel: {
    fontFamily: 'Gilroy',
    fontWeight: 600,
    fontSize: '14px',
    color: '#1A1A1A',
    mb: 1,
  },
  docPreviewBox: {
    width: 54,
    height: 54,
    border: '1px solid #DCE3FF',
    borderRadius: '4px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    backgroundColor: '#F8F9FA',
    '&:hover': {
      borderColor: '#002CBA',
    },
  },
  docPreviewBoxDisabled: {
    width: 54,
    height: 54,
    border: '1px solid #DCE3FF',
    borderRadius: '4px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F5F5F5',
    cursor: 'not-allowed',
  },
  docImageIcon: {
    fontSize: 28,
    color: '#666',
  },
  docPreviewNA: {
    fontSize: '12px',
    color: '#999',
    fontFamily: 'Gilroy',
  },
  actionButtons: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: 2,
    mt: 3,
    pt: 0,
  },
  rejectButton: {
    backgroundColor: '#fff',
    border: '1px solid #002CBA',
    color: '#002CBA',
    textTransform: 'none',
    px: 4,
    py: 1,
    borderRadius: '4px',
    fontFamily: 'Gilroy',
    fontSize: '14px',
    '&:hover': {
      backgroundColor: '#f5f5f5',
      border: '1px solid #002CBA',
    },
  },
  approveButton: {
    backgroundColor: '#002CBA',
    color: '#fff',
    textTransform: 'none',
    px: 4,
    py: 1,
    borderRadius: '4px',
    fontFamily: 'Gilroy',
    fontSize: '14px',
    '&:hover': {
      backgroundColor: 'rgba(0, 44, 186, 0.9)',
    },
  },
  modalBox: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    width: 400,
    bgcolor: 'background.paper',
    boxShadow: 24,
    p: 4,
    borderRadius: '8px',
    textAlign: 'center',
  },
  docViewContainer: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    zIndex: 1300,
    display: 'flex',
    flexDirection: 'column',
  },
  docViewHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '16px 24px',
    backgroundColor: '#fff',
    borderBottom: '1px solid #E6EBFF',
  },
  docViewTitle: {
    fontFamily: 'Gilroy',
    fontWeight: 600,
    fontSize: '18px',
    color: '#1A1A1A',
  },
  docViewCloseBtn: {
    color: '#002CBA',
    textTransform: 'none',
    fontFamily: 'Gilroy',
    fontWeight: 600,
  },
  docViewBody: {
    flex: 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f5f5f5',
    padding: '24px',
    overflow: 'auto',
  },
  docViewLoader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: '200px',
  },
};
